/**
 * Build data/study/intermediate-2.json — Intermediate L2 (real-world interaction).
 * Spec: 25–30 decks × 12–14 cards, 300–360 total. English-primary fronts (`prompt-locale-policy.ts`).
 * MCQ-friendly: prefer a single `___` aligned with `backEn` where practical.
 *
 *   yarn study:build-intermediate2-json
 */
import fs from "node:fs";
import path from "node:path";
import { intermediate2LevelFileSchema } from "../src/lib/study/schemas";

const OUT = path.join(__dirname, "../data/study/intermediate-2.json");

type Pair = [string, string];

const CARDS = 12;

function D(deck: string, xs: Pair[]): Pair[] {
  if (xs.length !== CARDS) throw new Error(`${deck}: expected ${CARDS} cards, got ${xs.length}`);
  return xs;
}

const T = (ja: string, en: string): Pair => [`Translate: ${ja}`, en];

/** 28 decks × 12 = 336 cards (within 300–360). */
const DECK_SPECS: { titleJa: string; titleEn: string; cards: Pair[] }[] = [
  {
    titleJa: "条件文①（if + 現在形）",
    titleEn: "Conditionals (1) — if + present",
    cards: D("If+present 1", [
      ["If it ___ tomorrow, I will stay home.", "If it rains tomorrow, I will stay home."],
      ["If the train ___ late, we'll miss the connection.", "If the train is late, we'll miss the connection."],
      ["If you ___ the file now, I'll review it tonight.", "If you send the file now, I'll review it tonight."],
      ["If you heat the soup, ___ it so it doesn't burn.", "If you heat the soup, stir it so it doesn't burn."],
      ["If there isn't enough room, we ___ use the other room.", "If there isn't enough room, we'll use the other room."],
      T("もし時間があれば、コーヒーでもどうですか。", "If you have time, how about a coffee?"),
      ["Unless it stops raining, we can't ___ the match on time.", "Unless it stops raining, we can't start the match on time."],
      ["I'll call you if anything ___ .", "I'll call you if anything changes."],
      T("彼が来なければ、始めましょう。", "If he doesn't come, let's start."),
      ["If you're not sure, ___ ask the staff.", "If you're not sure, just ask the staff."],
      ["We'll postpone the picnic if the wind ___ too strong.", "We'll postpone the picnic if the wind is too strong."],
      T("もし迷ったら、地図アプリを見てください。", "If you get lost, check the map app."),
    ]),
  },
  {
    titleJa: "条件文②（will / 提案）",
    titleEn: "Conditionals (2) — plans & offers",
    cards: D("If+present 2", [
      ["If you wait here, I ___ get the manager.", "If you wait here, I'll get the manager."],
      ["If you need a receipt, I ___ print one for you.", "If you need a receipt, I'll print one for you."],
      ["If it's cheaper online, we ___ order there.", "If it's cheaper online, we'll order there."],
      T("もしよければ、席をご案内します。", "If you like, I can show you to your seat."),
      ["If the meeting runs long, ___ take a taxi home.", "If the meeting runs long, I'll take a taxi home."],
      ["If you see Yuki, ___ her I'm running five minutes late.", "If you see Yuki, tell her I'm running five minutes late."],
      T("雨が降ったら、室内でやりましょう。", "If it rains, let's do it indoors."),
      ["If there's no reply by Friday, ___ follow up by email.", "If there's no reply by Friday, I'll follow up by email."],
      ["If you ___ uncomfortable, say something right away.", "If you feel uncomfortable, say something right away."],
      T("都合が悪ければ、別の日にしましょう。", "If it's not convenient, let's pick another day."),
      ["If we leave now, we ___ catch the last train.", "If we leave now, we'll catch the last train."],
      ["If the package arrives damaged, ___ contact support.", "If the package arrives damaged, please contact support."],
    ]),
  },
  {
    titleJa: "条件文③（unless / provided）",
    titleEn: "Conditionals (3) — unless & provided",
    cards: D("Unless/provided", [
      ["___ you finish the checklist, you can't board early.", "Unless you finish the checklist, you can't board early."],
      ["I'll attend ___ something urgent comes up.", "I'll attend unless something urgent comes up."],
      T("彼が謝らない限り、許しません。", "I won't forgive him unless he apologizes."),
      ["You can use the lounge ___ you show your membership card.", "You can use the lounge provided you show your membership card."],
      ["We can ship today ___ the payment clears this afternoon.", "We can ship today provided the payment clears this afternoon."],
      T("招待されない限り、パーティーには行きません。", "I won't go to the party unless I'm invited."),
      ["Unless we hear otherwise, we'll ___ at 9 a.m.", "Unless we hear otherwise, we'll start at 9 a.m."],
      ["I'll keep the seat ___ someone needs it more.", "I'll keep the seat unless someone needs it more."],
      T("天気が良ければ、ハイキングに行きます。", "We'll go hiking as long as the weather is good."),
      ["You may leave early ___ your supervisor approves it.", "You may leave early provided your supervisor approves it."],
      ["Unless it's an emergency, ___ call after 10 p.m.", "Unless it's an emergency, don't call after 10 p.m."],
      T("問題がなければ、明日発送します。", "We'll ship tomorrow as long as there are no issues."),
    ]),
  },
  {
    titleJa: "丁寧な依頼①（Could you…）",
    titleEn: "Polite requests (1) — Could you…",
    cards: D("Could you 1", [
      ["___ you repeat that more slowly?", "Could you repeat that more slowly?"],
      ["___ you send me the agenda by noon?", "Could you send me the agenda by noon?"],
      ["___ you hold the door for a second?", "Could you hold the door for a second?"],
      T("窓を少し開けていただけますか。", "Could you open the window a little?"),
      ["___ you check whether my name is on the list?", "Could you check whether my name is on the list?"],
      ["___ you tell me which line goes to the airport?", "Could you tell me which line goes to the airport?"],
      T("こちらにお水をいただけますか。", "Could you bring us some water, please?"),
      ["___ you turn your microphone off when you're not speaking?", "Could you turn your microphone off when you're not speaking?"],
      ["___ you confirm the spelling of your surname?", "Could you confirm the spelling of your surname?"],
      T("写真を撮っていただけますか。", "Could you take a photo for us?"),
      ["___ you let me know if the schedule changes?", "Could you let me know if the schedule changes?"],
      ["___ you move your bag off the seat?", "Could you move your bag off the seat?"],
    ]),
  },
  {
    titleJa: "丁寧な依頼②（Would you mind…）",
    titleEn: "Polite requests (2) — Would you mind…",
    cards: D("Would you mind", [
      ["___ you mind closing the window? It's a bit cold.", "Would you mind closing the window? It's a bit cold."],
      ["___ you mind waiting for a few minutes?", "Would you mind waiting for a few minutes?"],
      ["___ if I sat here?", "Would you mind if I sat here?"],
      T("少し前に出ていただけますか。", "Would you mind stepping forward a little?"),
      ["___ you mind switching to the other line?", "Would you mind switching to the other line?"],
      ["___ if I used your charger?", "Would you mind if I used your charger?"],
      T("署名をこちらにお願いできますか。", "Would you mind signing here?"),
      ["___ you mind keeping your voice down?", "Would you mind keeping your voice down?"],
      ["___ if we started five minutes late?", "Would you mind if we started five minutes late?"],
      T("後ろのドアから降りていただけますか。", "Would you mind getting off through the rear door?"),
      ["___ you mind forwarding that email to me?", "Would you mind forwarding that email to me?"],
      ["___ if I took this chair?", "Would you mind if I took this chair?"],
    ]),
  },
  {
    titleJa: "依頼の和らげ方",
    titleEn: "Softening requests",
    cards: D("Softening", [
      ["I was ___ if you could review this tonight.", "I was wondering if you could review this tonight."],
      ["Would it be ___ to reschedule to Thursday?", "Would it be possible to reschedule to Thursday?"],
      ["I'm sorry to ___, but could you help me with this form?", "I'm sorry to bother you, but could you help me with this form?"],
      T("お忙しいところ恐れ入りますが、少しお時間よろしいでしょうか。", "Sorry to interrupt — do you have a moment?"),
      ["Do you ___ if I join you for lunch?", "Do you mind if I join you for lunch?"],
      ["Could I possibly ___ an extension until Monday?", "Could I possibly get an extension until Monday?"],
      T("差し支えなければ、お名前を教えていただけますか。", "If you don't mind, could I have your name?"),
      ["I don't want to ___, but this doesn't look right.", "I don't want to sound rude, but this doesn't look right."],
      ["Would you be ___ to share the link again?", "Would you be willing to share the link again?"],
      T("恐縮ですが、もう一度説明していただけますか。", "I'm embarrassed to ask, but could you explain that again?"),
      ["If it's not too much ___, could you double-check the total?", "If it's not too much trouble, could you double-check the total?"],
      ["I would ___ appreciate a quick reply when you can.", "I would really appreciate a quick reply when you can."],
    ]),
  },
  {
    titleJa: "比較①（-er / more … than）",
    titleEn: "Comparisons (1) — than",
    cards: D("Compare 1", [
      ["This route is ___ than the one we took yesterday.", "This route is faster than the one we took yesterday."],
      ["The sequel was ___ interesting than the first film.", "The sequel was more interesting than the first film."],
      ["Living downtown is ___ expensive than I expected.", "Living downtown is more expensive than I expected."],
      T("この店の方が駅の近くにあります。", "This shop is closer to the station than that one."),
      ["She speaks more confidently ___ she did last year.", "She speaks more confidently than she did last year."],
      ["I like this laptop ___ it's lighter than my old one.", "I like this laptop because it's lighter than my old one."],
      T("今日の方が昨日より暖かいです。", "Today is warmer than yesterday."),
      ["The new app is ___ complicated than the old version.", "The new app is less complicated than the old version."],
      ["He earns ___ than his colleague, but he works longer hours.", "He earns more than his colleague, but he works longer hours."],
      T("飛行機の方がバスより速いです。", "The plane is faster than the bus."),
      ["This coffee tastes ___ than the one I usually buy.", "This coffee tastes better than the one I usually buy."],
      ["The meeting was ___ than we thought it would be.", "The meeting was shorter than we thought it would be."],
    ]),
  },
  {
    titleJa: "比較②（最上級・意見）",
    titleEn: "Comparisons (2) — superlatives & opinions",
    cards: D("Superlatives", [
      ["That's ___ idea I've heard all week.", "That's the worst idea I've heard all week."],
      ["It was one of ___ concerts I've ever been to.", "It was one of the best concerts I've ever been to."],
      ["This is ___ option if you want to save money.", "This is the cheapest option if you want to save money."],
      T("この地域で一番静かな公園はどこですか。", "Where's the quietest park in this area?"),
      ["She's ___ person on the team right now.", "She's the busiest person on the team right now."],
      ["I think Tuesday works ___ for everyone.", "I think Tuesday works best for everyone."],
      T("これは今月で最も重要な締め切りです。", "This is the most important deadline this month."),
      ["That's ___ polite way to say no.", "That's a polite way to say no."],
      ["Of the three, I found the middle one ___ useful.", "Of the three, I found the middle one the most useful."],
      T("その中で一番好きなのはどれですか。", "Which one do you like the most?"),
      ["It's not ___ difficult topic we've covered.", "It's not the most difficult topic we've covered."],
      ["This hotel has ___ pool in town.", "This hotel has the nicest pool in town."],
    ]),
  },
  {
    titleJa: "比較③（as … as / 同程度）",
    titleEn: "Comparisons (3) — as … as",
    cards: D("As as", [
      ["This bag is ___ heavy as it looks.", "This bag is as heavy as it looks."],
      ["The copy isn't ___ clear as the original.", "The copy isn't as clear as the original."],
      ["Try to arrive ___ early as you can.", "Try to arrive as early as you can."],
      T("彼は兄と同じくらい背が高いです。", "He's as tall as his older brother."),
      ["The second sample is ___ as expensive.", "The second sample is nearly twice as expensive."],
      ["She doesn't talk ___ much as she used to.", "She doesn't talk as much as she used to."],
      T("想像していたほど難しくありませんでした。", "It wasn't as difficult as I imagined."),
      ["I'll stay ___ long as you need me.", "I'll stay as long as you need me."],
      ["The room was ___ big as we hoped.", "The room was as big as we hoped."],
      T("昨日と同じくらい混んでいます。", "It's as crowded as it was yesterday."),
      ["He's not ___ patient as his manager.", "He's not as patient as his manager."],
      ["Please pack ___ carefully as you can.", "Please pack as carefully as you can."],
    ]),
  },
  {
    titleJa: "問題を伝える",
    titleEn: "Problem-solving language",
    cards: D("Problems", [
      ["I have ___ with my reservation — it's under the wrong name.", "I have an issue with my reservation — it's under the wrong name."],
      ["Something is ___ with the Wi‑Fi; I can't connect.", "Something is wrong with the Wi‑Fi; I can't connect."],
      ["I'm having ___ getting the file to upload.", "I'm having trouble getting the file to upload."],
      T("お会計に誤りがあるようです。", "There seems to be a mistake on the bill."),
      ["The screen keeps ___ — could someone take a look?", "The screen keeps freezing — could someone take a look?"],
      ["This isn't ___ I ordered.", "This isn't what I ordered."],
      T("部屋のエアコンが動きません。", "The air conditioner in my room isn't working."),
      ["I'd like to ___ a complaint about the noise last night.", "I'd like to make a complaint about the noise last night."],
      ["We're running ___ a small problem with the delivery.", "We're running into a small problem with the delivery."],
      T("鍵が部屋で開きません。", "The key won't open the door to my room."),
      ["Could you help me ___ this out?", "Could you help me sort this out?"],
      ["I'm not sure what's ___, but the alarm won't stop.", "I'm not sure what's going on, but the alarm won't stop."],
    ]),
  },
  {
    titleJa: "解決・フォロー",
    titleEn: "Solutions & follow-up",
    cards: D("Solutions", [
      ["Let me ___ what we can do about this.", "Let me see what we can do about this."],
      ["I'll ___ this to the maintenance team right away.", "I'll report this to the maintenance team right away."],
      ["We can ___ you a replacement by tomorrow.", "We can send you a replacement by tomorrow."],
      T("申し訳ございません。すぐに確認します。", "I'm sorry — I'll check that right away."),
      ["If that doesn't work, ___ try restarting the router.", "If that doesn't work, let's try restarting the router."],
      ["I'll ___ you posted as soon as I hear back.", "I'll keep you posted as soon as I hear back."],
      T("別の部屋に移していただけますか。", "Could we move to a different room?"),
      ["Would a ___ be okay instead?", "Would a refund be okay instead?"],
      ["I'll ___ a note so it doesn't happen again.", "I'll leave a note so it doesn't happen again."],
      T("再発防止のため、記録を残します。", "I'll log this so we can prevent it from happening again."),
      ["Can we ___ on this tomorrow morning?", "Can we follow up on this tomorrow morning?"],
      ["Thanks for ___ — I appreciate your patience.", "Thanks for letting us know — I appreciate your patience."],
    ]),
  },
  {
    titleJa: "仕事①（会議）",
    titleEn: "Work (1) — meetings",
    cards: D("Meetings", [
      ["Sorry, I need to ___ — I have another call.", "Sorry, I need to go — I have another call."],
      ["Could we ___ the next slide?", "Could we move to the next slide?"],
      ["I'll ___ the action items at the end.", "I'll summarize the action items at the end."],
      T("本日の議題を確認してもよろしいでしょうか。", "Shall we go over today's agenda?"),
      ["___ we take a five-minute break?", "Can we take a five-minute break?"],
      ["I'm not sure I ___ that last point — could you clarify?", "I'm not sure I followed that last point — could you clarify?"],
      T("次回の会議は金曜の午後でよいですか。", "Is Friday afternoon okay for the next meeting?"),
      ["Let me ___ that back to you to check I understood.", "Let me feed that back to you to check I understood."],
      ["I'll ___ the minutes after the call.", "I'll circulate the minutes after the call."],
      T("発言したい方は挙手をお願いします。", "Please raise your hand if you'd like to speak."),
      ["We're slightly ___ schedule, so let's stay focused.", "We're slightly behind schedule, so let's stay focused."],
      ["Could everyone ___ their mics on mute unless speaking?", "Could everyone keep their mics on mute unless speaking?"],
    ]),
  },
  {
    titleJa: "仕事②（メール・連絡）",
    titleEn: "Work (2) — email & messages",
    cards: D("Email", [
      ["I'm writing to ___ about tomorrow's deadline.", "I'm writing to follow up about tomorrow's deadline."],
      ["Please find the report ___ .", "Please find the report attached."],
      ["Let me know if you need any ___ information.", "Let me know if you need any further information."],
      T("ご確認のほどよろしくお願いいたします。", "Thank you in advance for your review."),
      ["I'll ___ you a calendar invite this afternoon.", "I'll send you a calendar invite this afternoon."],
      ["Could you ___ me in copy on that thread?", "Could you add me in copy on that thread?"],
      T("返信が遅れて申し訳ありません。", "Sorry for the delayed reply."),
      ["I'm ___ of the office until Thursday.", "I'm out of the office until Thursday."],
      ["Just a quick ___ to confirm we received your payment.", "Just a quick note to confirm we received your payment."],
      T("添付ファイルが開けないのですが。", "I'm having trouble opening the attachment."),
      ["I'll ___ back to you by end of day.", "I'll get back to you by end of day."],
      ["Thanks ___ your patience while we investigate.", "Thanks for your patience while we investigate."],
    ]),
  },
  {
    titleJa: "仕事③（締切・優先）",
    titleEn: "Work (3) — deadlines & priorities",
    cards: D("Deadlines", [
      ["We're ___ against a tight deadline this week.", "We're up against a tight deadline this week."],
      ["Could we ___ the due date by one day?", "Could we extend the due date by one day?"],
      ["I'll ___ this task first thing tomorrow.", "I'll tackle this task first thing tomorrow."],
      T("最優先で対応してください。", "Please treat this as top priority."),
      ["If we can't finish today, we should ___ stakeholders early.", "If we can't finish today, we should flag stakeholders early."],
      ["Let's ___ what must be done today vs. next week.", "Let's break down what must be done today vs. next week."],
      T("スケジュールに余裕はありますか。", "Do we have any slack in the schedule?"),
      ["I'm blocked ___ I get approval from finance.", "I'm blocked until I get approval from finance."],
      ["Can we ___ resources for the launch next month?", "Can we allocate resources for the launch next month?"],
      T("この部分は後回しにしても大丈夫ですか。", "Is it okay to deprioritize this part?"),
      ["I'll ___ you a realistic timeline by noon.", "I'll give you a realistic timeline by noon."],
      ["We need to ___ expectations if the scope grows.", "We need to manage expectations if the scope grows."],
    ]),
  },
  {
    titleJa: "手順を説明①",
    titleEn: "Explaining processes (1)",
    cards: D("Process 1", [
      ["___, log in with your work email.", "First, log in with your work email."],
      ["___, open the settings tab.", "Then, open the settings tab."],
      ["___, click save and restart the app.", "Finally, click save and restart the app."],
      T("最初に袋から中身を全部出してください。", "First, take everything out of the bag."),
      ["After that, you should ___ a backup copy.", "After that, you should make a backup copy."],
      ["Before you start, ___ sure the device is charged.", "Before you start, make sure the device is charged."],
      T("次に、電源ボタンを長押しします。", "Next, hold the power button down."),
      ["Once the light turns green, you can ___ the cable.", "Once the light turns green, you can unplug the cable."],
      ["If anything looks odd, ___ the process and call us.", "If anything looks odd, stop the process and call us."],
      T("最後に、蓋をしっかり閉めてください。", "Lastly, close the lid tightly."),
      ["The next ___ is to verify your identity.", "The next step is to verify your identity."],
      ["At this point, you ___ wait about two minutes.", "At this point, you should wait about two minutes."],
    ]),
  },
  {
    titleJa: "手順を説明②",
    titleEn: "Explaining processes (2)",
    cards: D("Process 2", [
      ["___, rinse the rice until the water runs clear.", "First, rinse the rice until the water runs clear."],
      ["___, add water up to the line inside the pot.", "Next, add water up to the line inside the pot."],
      ["___, let it rest for ten minutes before opening.", "Finally, let it rest for ten minutes before opening."],
      T("その後、よく混ぜてください。", "After that, mix it well."),
      ["When you're done, ___ the tools in the sink.", "When you're done, leave the tools in the sink."],
      ["Until the beep sounds, don't ___ the lid.", "Until the beep sounds, don't open the lid."],
      T("準備ができたら知らせてください。", "Let me know when you're ready."),
      ["Meanwhile, ___ the vegetables on the side.", "Meanwhile, chop the vegetables on the side."],
      ["By the time it boils, the sauce ___ be ready.", "By the time it boils, the sauce should be ready."],
      T("問題があれば途中で止めてください。", "If there's a problem, stop halfway."),
      ["Afterward, we can ___ the results together.", "Afterward, we can review the results together."],
      ["In the meantime, feel ___ to grab coffee.", "In the meantime, feel free to grab coffee."],
    ]),
  },
  {
    titleJa: "過去の経験①",
    titleEn: "Past experiences (1)",
    cards: D("Past 1", [
      ["I went to Kyoto last spring, and it ___ amazing.", "I went to Kyoto last spring, and it was amazing."],
      ["We tried that new café, but it ___ too crowded.", "We tried that new café, but it was too crowded."],
      ["I ___ there once on business.", "I've been there once on business."],
      T("週末に友達とキャンプに行きました。", "I went camping with friends over the weekend."),
      ["It was the first time I ___ sushi in Japan.", "It was the first time I ate sushi in Japan."],
      ["After the concert, we ___ for a walk by the river.", "After the concert, we went for a walk by the river."],
      T("子供の頃、毎年海に行っていました。", "When I was a child, we went to the beach every year."),
      ["I didn't expect the hike to be ___ tiring.", "I didn't expect the hike to be this tiring."],
      ["Last year I ___ a short course online.", "Last year I took a short course online."],
      T("その時、とても緊張していました。", "At that time, I was really nervous."),
      ["We got ___ late because of traffic.", "We got home late because of traffic."],
      ["I ___ a lot of photos, but I lost my phone.", "I took a lot of photos, but I lost my phone."],
    ]),
  },
  {
    titleJa: "過去の経験②",
    titleEn: "Past experiences (2)",
    cards: D("Past 2", [
      ["When I arrived, the store ___ already closed.", "When I arrived, the store was already closed."],
      ["While we were waiting, it ___ to rain.", "While we were waiting, it started to rain."],
      ["After I finished work, I ___ straight home.", "After I finished work, I went straight home."],
      T("会議が終わった後、食事に行きました。", "After the meeting, we went out for dinner."),
      ["I was about to leave ___ someone called my name.", "I was about to leave when someone called my name."],
      ["By the time we got there, the show ___ sold out.", "By the time we got there, the show was sold out."],
      T("その日はとても忙しい一日でした。", "It was a really busy day."),
      ["I ___ never seen snow before that trip.", "I had never seen snow before that trip."],
      ["We ___ lost for an hour near the station.", "We got lost for an hour near the station."],
      T("楽しかったですが、疲れました。", "It was fun, but I was exhausted."),
      ["I ___ I'd booked a window seat.", "I wish I'd booked a window seat."],
      ["In the end, we ___ a taxi because we were late.", "In the end, we took a taxi because we were late."],
    ]),
  },
  {
    titleJa: "ストーリーをつなぐ",
    titleEn: "Storytelling connectors",
    cards: D("Story conn", [
      ["___ we left the house, we realized we'd forgotten tickets.", "As soon as we left the house, we realized we'd forgotten the tickets."],
      ["___ the train arrived, everyone rushed to the doors.", "When the train arrived, everyone rushed to the doors."],
      ["___ that, we decided to walk instead.", "After that, we decided to walk instead."],
      T("突然、雨が降り始めました。", "Suddenly, it started to rain."),
      ["___ we were chatting, the lights went out.", "While we were chatting, the lights went out."],
      ["___ the end, everything worked out fine.", "In the end, everything worked out fine."],
      T("幸いなことに、誰も怪我をしませんでした。", "Luckily, nobody was hurt."),
      ["___ a result, we missed the opening act.", "As a result, we missed the opening act."],
      ["___ first I was nervous, but then I relaxed.", "At first I was nervous, but then I relaxed."],
      T("結局、自分でやってみることにしました。", "Eventually, I decided to try it myself."),
      ["___ moment we sat down, the show began.", "The moment we sat down, the show began."],
      ["___ hearing the news, she called her parents.", "On hearing the news, she called her parents."],
    ]),
  },
  {
    titleJa: "助言①（should / ought）",
    titleEn: "Advice (1) — should / ought to",
    cards: D("Advice 1", [
      ["You ___ get some rest — you sound exhausted.", "You should get some rest — you sound exhausted."],
      ["He ought to ___ a doctor about that cough.", "He ought to see a doctor about that cough."],
      ["We should probably ___ earlier if we want good seats.", "We should probably leave earlier if we want good seats."],
      T("その前にもう一度確認した方がいいです。", "You should double-check that beforehand."),
      ["You shouldn't ___ passwords in chat.", "You shouldn't share passwords in chat."],
      ["I think you ___ talk to HR about the schedule.", "I think you should talk to HR about the schedule."],
      T("そんなに無理をしない方がいいですよ。", "You ought not to push yourself so hard."),
      ["They should ___ notified us about the closure.", "They should have notified us about the closure."],
      ["You might want to ___ a jacket — it's cold outside.", "You might want to bring a jacket — it's cold outside."],
      T("正直に言った方がいいと思います。", "I think you should be honest about it."),
      ["We ought to ___ thank the host before we leave.", "We ought to thank the host before we leave."],
      ["If I were you, I'd ___ a backup plan.", "If I were you, I'd keep a backup plan."],
    ]),
  },
  {
    titleJa: "助言②（Why don't you / How about）",
    titleEn: "Advice (2) — suggestions",
    cards: D("Advice 2", [
      ["___ you try the vegetarian option?", "Why don't you try the vegetarian option?"],
      ["___ meeting on Zoom instead of in person?", "How about meeting on Zoom instead of in person?"],
      ["___ we split the bill evenly?", "Why don't we split the bill evenly?"],
      T("一度相談してみたらどうですか。", "How about talking to them once?"),
      ["___ taking a short walk before dinner?", "How about taking a short walk before dinner?"],
      ["___ you ask at the information desk?", "Why don't you ask at the information desk?"],
      T("明日の午後はどうですか。", "How about tomorrow afternoon?"),
      ["___ we grab coffee after this?", "Shall we grab coffee after this?"],
      ["Maybe you could ___ a day off social media.", "Maybe you could take a day off social media."],
      T("別の店を試してみませんか。", "Why not try another shop?"),
      ["I'd suggest ___ the train if traffic is bad.", "I'd suggest taking the train if traffic is bad."],
      ["Have you thought ___ joining the weekend workshop?", "Have you thought about joining the weekend workshop?"],
    ]),
  },
  {
    titleJa: "助言③（提案の言い方）",
    titleEn: "Advice (3) — framing suggestions",
    cards: D("Advice 3", [
      ["One option ___ be to postpone the launch.", "One option might be to postpone the launch."],
      ["It ___ be worth comparing prices online.", "It might be worth comparing prices online."],
      ["I'd ___ keeping a copy on a USB drive.", "I'd recommend keeping a copy on a USB drive."],
      T("個人的には、もう少し待つべきだと思います。", "Personally, I think we should wait a bit longer."),
      ["If you ask me, we ___ focus on quality first.", "If you ask me, we should focus on quality first."],
      ["My ___ would be to start with the basics.", "My advice would be to start with the basics."],
      T("試しにやってみる価値はあると思います。", "I think it's worth giving it a try."),
      ["You could always ___ for help if you get stuck.", "You could always ask for help if you get stuck."],
      ["Perhaps we should ___ the scope smaller.", "Perhaps we should keep the scope smaller."],
      T("急がず、一つずつ進めましょう。", "Let's take it step by step without rushing."),
      ["I wouldn't ___ skipping the safety check.", "I wouldn't recommend skipping the safety check."],
      ["Let's ___ it simple for the first version.", "Let's keep it simple for the first version."],
    ]),
  },
  {
    titleJa: "抽象語彙①",
    titleEn: "Abstract vocabulary (1)",
    cards: D("Abstract 1", [
      ["We need a clear ___ before we spend more money.", "We need a clear plan before we spend more money."],
      ["That was a tough ___, but I'm glad we made it.", "That was a tough decision, but I'm glad we made it."],
      ["The ___ of the project exceeded our expectations.", "The result of the project exceeded our expectations."],
      T("そのアイデアは実現可能だと思います。", "I think that idea is feasible."),
      ["She explained the ___ behind the change.", "She explained the reason behind the change."],
      ["Let's discuss the ___ and cons calmly.", "Let's discuss the pros and cons calmly."],
      T("結果を踏まえて方針を変えましょう。", "Let's adjust our approach based on the outcome."),
      ["We don't have enough ___ to hire two people.", "We don't have enough budget to hire two people."],
      ["His ___ attitude helped the team stay calm.", "His positive attitude helped the team stay calm."],
      T("優先順位をはっきりさせましょう。", "Let's clarify our priorities."),
      ["The main ___ is whether we can meet the deadline.", "The main issue is whether we can meet the deadline."],
      ["We reached ___ after a long discussion.", "We reached an agreement after a long discussion."],
    ]),
  },
  {
    titleJa: "抽象語彙②",
    titleEn: "Abstract vocabulary (2)",
    cards: D("Abstract 2", [
      ["There's been a change ___ schedule.", "There's been a change of schedule."],
      ["We need your ___ on the new policy.", "We need your feedback on the new policy."],
      ["The team showed great ___ under pressure.", "The team showed great cooperation under pressure."],
      T("進捗を共有していただけますか。", "Could you share the progress with us?"),
      ["Let's set realistic ___ for this quarter.", "Let's set realistic goals for this quarter."],
      ["We should document the ___ so nothing is forgotten.", "We should document the process so nothing is forgotten."],
      T("リスクを最小限に抑えましょう。", "Let's minimize the risk."),
      ["The ___ of this tool is to save time.", "The purpose of this tool is to save time."],
      ["We learned a valuable ___ from that mistake.", "We learned a valuable lesson from that mistake."],
      T("期待値をそろえましょう。", "Let's align our expectations."),
      ["There's no simple ___ to this problem.", "There's no simple solution to this problem."],
      ["We need more ___ before we decide.", "We need more information before we decide."],
    ]),
  },
  {
    titleJa: "電話・通話",
    titleEn: "Telephone & calls",
    cards: D("Phone", [
      ["___ you hear me okay?", "Can you hear me okay?"],
      ["Sorry, you're ___ — could you say that again?", "Sorry, you're breaking up — could you say that again?"],
      ["I'll ___ it to you by email right after this call.", "I'll send it to you by email right after this call."],
      T("お電話ありがとうございます。田中と申します。", "Thank you for calling. This is Tanaka speaking."),
      ["Could I speak to someone ___ billing?", "Could I speak to someone in billing?"],
      ["I'll ___ you through to the right department.", "I'll transfer you through to the right department."],
      T("今ちょっと手が離せないので、後でかけ直します。", "I can't talk right now — I'll call you back later."),
      ["The line went ___ for a second.", "The line went dead for a second."],
      ["Let me ___ you back in five minutes.", "Let me call you back in five minutes."],
      T("お待ちください。つなぎます。", "Please hold — I'll connect you."),
      ["I didn't ___ your name — could you spell it?", "I didn't catch your name — could you spell it?"],
      ["We're having ___ issues with the audio today.", "We're having technical issues with the audio today."],
    ]),
  },
  {
    titleJa: "オンライン会議・チャット",
    titleEn: "Online meetings & chat",
    cards: D("Online", [
      ["I think you're still ___ — we can't see your slides.", "I think you're still muted — we can't see your slides."],
      ["Could you ___ your camera on?", "Could you turn your camera on?"],
      ["I'll ___ the link in the chat.", "I'll paste the link in the chat."],
      T("画面共有をお願いできますか。", "Could you share your screen?"),
      ["Sorry, I had to ___ off video — bad signal.", "Sorry, I had to turn off video — bad signal."],
      ["Let's ___ the recording for people who missed it.", "Let's save the recording for people who missed it."],
      T("チャットに質問を書いてください。", "Please type your question in the chat."),
      ["I'll follow up ___ the thread after the call.", "I'll follow up in the thread after the call."],
      ["Can everyone see the ___ I'm sharing?", "Can everyone see the document I'm sharing?"],
      T("回線が不安定なので、音声のみで参加します。", "My connection is unstable, so I'll join audio only."),
      ["I'll ___ the meeting now — thanks everyone.", "I'll leave the meeting now — thanks everyone."],
      ["Could you ___ that message one more time?", "Could you resend that message one more time?"],
    ]),
  },
  {
    titleJa: "旅行①（空港・移動）",
    titleEn: "Travel (1) — airport & transit",
    cards: D("Travel 1", [
      ["Where do I ___ in for an international flight?", "Where do I check in for an international flight?"],
      ["My flight was ___ — what are my options?", "My flight was canceled — what are my options?"],
      ["Is this the ___ gate for the flight to Seattle?", "Is this the correct gate for the flight to Seattle?"],
      T("手荷物はどこで受け取りますか。", "Where do I pick up my luggage?"),
      ["How early should I ___ at the airport?", "How early should I arrive at the airport?"],
      ["I'd like an ___ seat, please.", "I'd like an aisle seat, please."],
      T("このバスは空港に行きますか。", "Does this bus go to the airport?"),
      ["Could you help me ___ this ticket machine?", "Could you help me with this ticket machine?"],
      ["I ___ my passport at the hotel.", "I left my passport at the hotel."],
      T("乗り換えはどの番線ですか。", "Which platform is my connection from?"),
      ["The security line is ___ than I expected.", "The security line is longer than I expected."],
      ["We need to ___ terminals before the next flight.", "We need to change terminals before the next flight."],
    ]),
  },
  {
    titleJa: "旅行②（ホテル・道順）",
    titleEn: "Travel (2) — hotel & directions",
    cards: D("Travel 2", [
      ["I have a reservation ___ Tanaka.", "I have a reservation under Tanaka."],
      ["Could we ___ a late checkout?", "Could we get a late checkout?"],
      ["Is breakfast ___ in the rate?", "Is breakfast included in the rate?"],
      T("駅まで歩いてどのくらいですか。", "How far is it to walk to the station?"),
      ["___ me, how do I get to the museum from here?", "Excuse me, how do I get to the museum from here?"],
      ["Is it ___ to walk at night in this area?", "Is it safe to walk at night in this area?"],
      T("この道をまっすぐ行って、二つ目を右です。", "Go straight on this road and turn right at the second light."),
      ["Turn ___ at the corner and you'll see the sign.", "Turn left at the corner and you'll see the sign."],
      ["It's about a ten-minute ___ from here.", "It's about a ten-minute walk from here."],
      T("地図アプリではここが目的地と違います。", "The map app says this isn't the right place."),
      ["Could you ___ a taxi for two people?", "Could you call a taxi for two people?"],
      ["I think we're ___ — we passed this shop already.", "I think we're lost — we passed this shop already."],
    ]),
  },
];

function build() {
  if (DECK_SPECS.length !== 28) {
    throw new Error(`Expected 28 decks, got ${DECK_SPECS.length}`);
  }
  const total = DECK_SPECS.reduce((s, d) => s + d.cards.length, 0);
  if (total !== 336) throw new Error(`Expected 336 cards, got ${total}`);

  const decks = DECK_SPECS.map((spec, di) => {
    const id = `study-i2-deck-${di}`;
    return {
      id,
      titleJa: spec.titleJa,
      titleEn: spec.titleEn,
      sortOrder: di,
      cards: spec.cards.map(([frontJa, backEn], ci) => ({
        id: `study-i2-d${di}-c${ci}`,
        frontJa,
        backEn,
        sortOrder: ci,
      })),
    };
  });

  const assessment = {
    passingScore: 72,
    items: [
      {
        id: "study-i2-a0",
        promptJa: "「If it rains tomorrow, I will stay home.」に最も近い文は？",
        promptEn: "Which sentence is closest to a first conditional about rain and staying home?",
        options: [
          "If it will rain tomorrow, I stay home.",
          "If it rains tomorrow, I will stay home.",
          "If it rained tomorrow, I will stay home.",
          "If it rains tomorrow, I would stay home.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a1",
        promptJa: "丁寧な依頼として自然なのは？",
        promptEn: "Which is a natural polite request?",
        options: [
          "You close the window now.",
          "Could you close the window, please?",
          "Close window please immediate.",
          "Window close you.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a2",
        promptJa: "比較として正しいのは？",
        promptEn: "Which comparison is grammatically correct?",
        options: [
          "This book is more better than that one.",
          "This book is better than that one.",
          "This book is gooder than that one.",
          "This book is more good than that one.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a3",
        promptJa: "問題を伝える表現として自然なのは？",
        promptEn: "Which line naturally reports a problem?",
        options: [
          "I have wrong with my room.",
          "Something is wrong with my room.",
          "My room is something wrong.",
          "Wrong is my room something.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a4",
        promptJa: "会議で使える表現はどれ？",
        promptEn: "Which phrase fits a work meeting?",
        options: [
          "Could we move to the next slide?",
          "Next slide now force.",
          "Slide go next must.",
          "We nexting slide.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i2-a5",
        promptJa: "手順の並びとして自然なのは？",
        promptEn: "Which sequence sounds natural for instructions?",
        options: [
          "Finally, first, then restart.",
          "First log in, then open settings, finally save.",
          "Then first finally settings.",
          "Save first finally then.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a6",
        promptJa: "過去の体験を述べる文として自然なのは？",
        promptEn: "Which sentence naturally describes a past experience?",
        options: [
          "I go to Kyoto and it amazing.",
          "I went to Kyoto, and it was amazing.",
          "I going Kyoto amazing was.",
          "Kyoto I went amazing it.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a7",
        promptJa: "助言として自然なのは？",
        promptEn: "Which is natural advice?",
        options: [
          "You must to see a doctor.",
          "You should see a doctor.",
          "You should seeing a doctor.",
          "Should you doctor see.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a8",
        promptJa: "電話で聞こえにくいとき、自然なのは？",
        promptEn: "Which line is natural on a bad phone line?",
        options: [
          "Can you hear me okay?",
          "You hear can me?",
          "Hear me you can okay?",
          "Me hear can okay you?",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i2-a9",
        promptJa: "空港でチェックインを尋ねる表現は？",
        promptEn: "Which asks where to check in at the airport?",
        options: [
          "Where I check in international?",
          "Where do I check in for an international flight?",
          "Check in where international I?",
          "International where check?",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a10",
        promptJa: "「Would you mind closing the window?」に近い丁寧さは？",
        promptEn: "Which request is similarly polite?",
        options: [
          "Close the window now.",
          "Would you mind closing the window?",
          "You mind window close.",
          "Window close mind you.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i2-a11",
        promptJa: "抽象名詞の使い方として自然なのは？",
        promptEn: "Which uses abstract nouns naturally?",
        options: [
          "We need a clear idea before a decision.",
          "We need clear idea before decision without article.",
          "We need idea clear a decision.",
          "Decision idea we need clear.",
        ],
        correctIndex: 0,
      },
    ],
  };

  const doc = {
    version: 1 as const,
    levelCode: "INTERMEDIATE_2" as const,
    decks,
    assessment,
  };

  const parsed = intermediate2LevelFileSchema.safeParse(doc);
  if (!parsed.success) {
    console.error(parsed.error.flatten());
    throw new Error("intermediate2LevelFileSchema validation failed");
  }

  fs.writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`, "utf8");
  console.log(`Wrote ${OUT} (${decks.length} decks, ${total} cards)`);
}

build();
