/**
 * Build data/study/intermediate-3.json — Intermediate L3 (clear expression).
 * Spec: 30–35 decks × 14–16 cards, 400–500 total. English-primary prompts.
 *
 *   yarn study:build-intermediate3-json
 */
import fs from "node:fs";
import path from "node:path";
import { inferReorderExerciseFromBlankPrompt } from "../src/lib/study/card-exercise";
import { intermediate3LevelFileSchema } from "../src/lib/study/schemas";

const OUT = path.join(__dirname, "../data/study/intermediate-3.json");

type Pair = [string, string];
const N = 15;

type FB = { f: string; b: string };

function deck(titleJa: string, titleEn: string, xs: FB[]): { titleJa: string; titleEn: string; cards: Pair[] } {
  if (xs.length !== N) throw new Error(`${titleEn}: need ${N} cards, got ${xs.length}`);
  return { titleJa, titleEn, cards: xs.map((x) => [x.f, x.b] as Pair) };
}

const T = (ja: string, en: string): FB => ({ f: `Translate: ${ja}`, b: en });

/** Decks × 15 cards each (within 30–35 decks, 400–500 total). */
const SPECS = [
  deck("複文① although", "Complex sentences — although (1)", [
    { f: "___ it was cold, we still sat on the terrace.", b: "Although it was cold, we still sat on the terrace." },
    { f: "___ the ticket was expensive, the show was worth it.", b: "Although the ticket was expensive, the show was worth it." },
    { f: "___ she was nervous, her presentation was clear.", b: "Although she was nervous, her presentation was clear." },
    { f: "___ traffic was heavy, we arrived on time.", b: "Although traffic was heavy, we arrived on time." },
    { f: "___ I disagree with the plan, I will support the team.", b: "Although I disagree with the plan, I will support the team." },
    T("疲れていたが、最後まで参加した。", "Although I was tired, I stayed until the end."),
    { f: "___ the data is incomplete, the trend looks positive.", b: "Although the data is incomplete, the trend looks positive." },
    { f: "___ he apologized, some colleagues remain upset.", b: "Although he apologized, some colleagues remain upset." },
    { f: "___ it's a small detail, it affects the whole design.", b: "Although it's a small detail, it affects the whole design." },
    T("予算は限られているが、質は落としたくない。", "Although the budget is tight, we don't want to cut quality."),
    { f: "___ we had practiced, the first question surprised us.", b: "Although we had practiced, the first question surprised us." },
    { f: "___ the restaurant was busy, the service stayed friendly.", b: "Although the restaurant was busy, the service stayed friendly." },
    { f: "___ I had sent a reminder, a few people forgot.", b: "Although I had sent a reminder, a few people forgot." },
    { f: "___ the risk is low, we should document it.", b: "Although the risk is low, we should document it." },
    T("年齢は若いが、とても責任感がある。", "Although she is young, she is very responsible."),
  ]),
  deck("複文② although", "Complex sentences — although (2)", [
    { f: "___ it sounds simple, implementation will take weeks.", b: "Although it sounds simple, implementation will take weeks." },
    { f: "___ we lost the first game, we reached the final.", b: "Although we lost the first game, we reached the final." },
    { f: "___ the museum was crowded, we enjoyed the exhibit.", b: "Although the museum was crowded, we enjoyed the exhibit." },
    { f: "___ I had doubts, the results convinced me.", b: "Although I had doubts, the results convinced me." },
    { f: "___ the flight was delayed, we made our connection.", b: "Although the flight was delayed, we made our connection." },
    T("反対は多かったが、案は可決された。", "Although there was a lot of opposition, the proposal was approved."),
    { f: "___ the software is old, it rarely crashes.", b: "Although the software is old, it rarely crashes." },
    { f: "___ he works remotely, he attends every stand-up.", b: "Although he works remotely, he attends every stand-up." },
    { f: "___ winter here is mild, we still get snow.", b: "Although winter here is mild, we still get snow." },
    { f: "___ the sample is small, the pattern is clear.", b: "Although the sample is small, the pattern is clear." },
    T("経験は浅いが、学ぶ意欲は高い。", "Although his experience is limited, he is eager to learn."),
    { f: "___ the deadline moved, the scope did not shrink.", b: "Although the deadline moved, the scope did not shrink." },
    { f: "___ she speaks softly, people listen carefully.", b: "Although she speaks softly, people listen carefully." },
    { f: "___ costs rose, we stayed within the cap.", b: "Although costs rose, we stayed within the cap." },
    { f: "___ I had warned them, they tried the shortcut.", b: "Although I had warned them, they tried the shortcut." },
  ]),
  deck("複文③ even though", "Complex sentences — even though (1)", [
    { f: "___ I set two alarms, I overslept.", b: "Even though I set two alarms, I overslept." },
    { f: "___ we rehearsed, I forgot my line on stage.", b: "Even though we rehearsed, I forgot my line on stage." },
    { f: "___ it was a weekday, the beach was packed.", b: "Even though it was a weekday, the beach was packed." },
    { f: "___ he studied hard, the exam felt unfair.", b: "Even though he studied hard, the exam felt unfair." },
    { f: "___ she saved money, she couldn't afford the repair.", b: "Even though she saved money, she couldn't afford the repair." },
    T("注意されたのに、同じミスをした。", "Even though I had been warned, I made the same mistake."),
    { f: "___ we left early, traffic was still awful.", b: "Even though we left early, traffic was still awful." },
    { f: "___ the instructions were clear, I assembled it wrong.", b: "Even though the instructions were clear, I assembled it wrong." },
    { f: "___ they offered a discount, I didn't buy it.", b: "Even though they offered a discount, I didn't buy it." },
    { f: "___ I locked the door, I worried all night.", b: "Even though I locked the door, I worried all night." },
    T("証拠があったのに、信じてもらえなかった。", "Even though there was evidence, they didn't believe me."),
    { f: "___ the path was steep, we reached the summit.", b: "Even though the path was steep, we reached the summit." },
    { f: "___ I muted my mic, background noise leaked in.", b: "Even though I muted my mic, background noise leaked in." },
    { f: "___ we doubled the staff, queues remained long.", b: "Even though we doubled the staff, queues remained long." },
    { f: "___ he had a visa, border control questioned him.", b: "Even though he had a visa, border control questioned him." },
  ]),
  deck("複文④ even though", "Complex sentences — even though (2)", [
    { f: "___ I don't drink coffee, I love the smell.", b: "Even though I don't drink coffee, I love the smell." },
    { f: "___ the forecast was sunny, we packed rain gear.", b: "Even though the forecast was sunny, we packed rain gear." },
    { f: "___ she had retired, she mentored new hires.", b: "Even though she had retired, she mentored new hires." },
    { f: "___ the room was small, the acoustics were great.", b: "Even though the room was small, the acoustics were great." },
    { f: "___ I had eaten, I was still hungry.", b: "Even though I had eaten, I was still hungry." },
    T("忙しかったのに、手伝ってくれた。", "Even though she was busy, she helped me."),
    { f: "___ we signed a contract, they changed the terms.", b: "Even though we signed a contract, they changed the terms." },
    { f: "___ the movie got bad reviews, I enjoyed it.", b: "Even though the movie got bad reviews, I enjoyed it." },
    { f: "___ he trains daily, injuries slowed him down.", b: "Even though he trains daily, injuries slowed him down." },
    { f: "___ I explained twice, he looked confused.", b: "Even though I explained twice, he looked confused." },
    { f: "___ the laptop is old, it runs smoothly.", b: "Even though the laptop is old, it runs smoothly." },
    { f: "___ we lowered the price, sales stayed flat.", b: "Even though we lowered the price, sales stayed flat." },
    { f: "___ she was a beginner, she finished the race.", b: "Even though she was a beginner, she finished the race." },
    { f: "___ I turned notifications off, I checked my phone.", b: "Even though I turned notifications off, I checked my phone." },
    { f: "___ winter had ended, snow fell in April.", b: "Even though winter had ended, snow fell in April." },
  ]),
  deck("複文⑤ while（対比）", "Complex sentences — while (contrast)", [
    { f: "___ I respect his work, I can't agree with this decision.", b: "While I respect his work, I can't agree with this decision." },
    { f: "___ the idea is creative, it isn't practical yet.", b: "While the idea is creative, it isn't practical yet." },
    { f: "___ costs have fallen, quality has improved.", b: "While costs have fallen, quality has improved." },
    { f: "___ some regions grew fast, others stagnated.", b: "While some regions grew fast, others stagnated." },
    { f: "___ I understand the urgency, we need more data.", b: "While I understand the urgency, we need more data." },
    T("彼は慎重だが、チームはスピードを求めている。", "While he is cautious, the team wants to move faster."),
    { f: "___ the app is popular, support tickets keep rising.", b: "While the app is popular, support tickets keep rising." },
    { f: "___ exports rose, domestic sales slipped.", b: "While exports rose, domestic sales slipped." },
    { f: "___ I sympathize with them, policy won't change.", b: "While I sympathize with them, policy won't change." },
    { f: "___ the headline looks scary, the risk is contained.", b: "While the headline looks scary, the risk is contained." },
    T("若者は増えている一方で、高齢者も増えている。", "While the youth population is growing, the elderly population is growing too."),
    { f: "___ we celebrate the win, we should review mistakes.", b: "While we celebrate the win, we should review mistakes." },
    { f: "___ demand is strong, supply chains remain fragile.", b: "While demand is strong, supply chains remain fragile." },
    { f: "___ she prefers text, clients want calls.", b: "While she prefers text, clients want calls." },
    { f: "___ the city is expensive, it offers opportunities.", b: "While the city is expensive, it offers opportunities." },
  ]),
  deck("複文⑥ while（同時）", "Complex sentences — while (simultaneous)", [
    { f: "___ I was cooking, the phone rang.", b: "While I was cooking, the phone rang." },
    { f: "___ they were debating, I took notes.", b: "While they were debating, I took notes." },
    { f: "___ we waited, the line barely moved.", b: "While we waited, the line barely moved." },
    { f: "___ she presented, the slides advanced automatically.", b: "While she presented, the slides advanced automatically." },
    { f: "___ I commuted, I listened to a podcast.", b: "While I commuted, I listened to a podcast." },
    T("彼が話している間、皆が静かに聞いていた。", "While he was speaking, everyone listened quietly."),
    { f: "___ the backup ran, we couldn't edit the file.", b: "While the backup ran, we couldn't edit the file." },
    { f: "___ it was raining, joggers kept circling the park.", b: "While it was raining, joggers kept circling the park." },
    { f: "___ you review this section, I'll handle the intro.", b: "While you review this section, I'll handle the intro." },
    { f: "___ the band tuned, the crowd cheered.", b: "While the band tuned, the crowd cheered." },
    T("工事が進む間、騒音が続いた。", "While construction continued, the noise went on."),
    { f: "___ he slept, his phone charged.", b: "While he slept, his phone charged." },
    { f: "___ we hiked, clouds rolled in.", b: "While we hiked, clouds rolled in." },
    { f: "___ the video rendered, I grabbed lunch.", b: "While the video rendered, I grabbed lunch." },
    { f: "___ they negotiated, lawyers reviewed the draft.", b: "While they negotiated, lawyers reviewed the draft." },
  ]),
  deck("第二条件①", "Second conditional — basics", [
    { f: "If I ___ more free time, I would travel more.", b: "If I had more free time, I would travel more." },
    { f: "If she ___ here, she would love this neighborhood.", b: "If she lived here, she would love this neighborhood." },
    { f: "If we ___ a bigger budget, we could hire two designers.", b: "If we had a bigger budget, we could hire two designers." },
    { f: "If it ___ warmer, we could eat outside tonight.", b: "If it were warmer, we could eat outside tonight." },
    { f: "If I ___ you, I would ask for a second opinion.", b: "If I were you, I would ask for a second opinion." },
    T("もし私が社長なら、方針を変えるだろう。", "If I were the CEO, I would change the strategy."),
    { f: "If the server ___ faster, the app would feel smoother.", b: "If the server were faster, the app would feel smoother." },
    { f: "If he ___ the truth, he would feel relieved.", b: "If he knew the truth, he would feel relieved." },
    { f: "If we ___ another week, we could polish the report.", b: "If we had another week, we could polish the report." },
    { f: "If this ___ my project, I would simplify the scope.", b: "If this were my project, I would simplify the scope." },
    T("もし時間が逆戻りできるなら、あの日に戻りたい。", "If I could turn back time, I would return to that day."),
    { f: "If they ___ stricter rules, fewer mistakes would happen.", b: "If they had stricter rules, fewer mistakes would happen." },
    { f: "If I ___ fluent, I would apply for that role.", b: "If I were fluent, I would apply for that role." },
    { f: "If the venue ___ larger, we could invite everyone.", b: "If the venue were larger, we could invite everyone." },
    { f: "If we ___ unlimited storage, we wouldn't delete files.", b: "If we had unlimited storage, we wouldn't delete files." },
  ]),
  deck("第二条件②", "Second conditional — wishes & hypotheticals", [
    { f: "If I ___ speak French, I could work in Montreal.", b: "If I could speak French, I could work in Montreal." },
    { f: "If she ___ join us, the discussion would be richer.", b: "If she could join us, the discussion would be richer." },
    { f: "If we ___ meet in person, I'd explain it better.", b: "If we could meet in person, I'd explain it better." },
    { f: "If nothing ___ in the way, we would launch in June.", b: "If nothing stood in the way, we would launch in June." },
    { f: "If I ___ one wish, I'd choose better work-life balance.", b: "If I had one wish, I'd choose better work-life balance." },
    T("もし雨が止めば、散歩に行くだろう。", "If the rain stopped, I would go for a walk."),
    { f: "If he ___ less shy, he would network more.", b: "If he were less shy, he would network more." },
    { f: "If the policy ___ different, morale might improve.", b: "If the policy were different, morale might improve." },
    { f: "If I ___ access to those logs, I could prove it.", b: "If I had access to those logs, I could prove it." },
    { f: "If it ___ not so late, I'd call her now.", b: "If it were not so late, I'd call her now." },
    T("もし君の立場なら、どうする？", "What would you do if you were in my position?"),
    { f: "If we ___ a mentor, we would avoid these pitfalls.", b: "If we had a mentor, we would avoid these pitfalls." },
    { f: "If the data ___ public, trust would erode.", b: "If the data were public, trust would erode." },
    { f: "If I ___ younger, I'd learn the piano.", b: "If I were younger, I'd learn the piano." },
    { f: "If the board ___ fully aligned, decisions would be faster.", b: "If the board were fully aligned, decisions would be faster." },
  ]),
  deck("第二条件③", "Second conditional — advice & critique", [
    { f: "If I ___ managing this team, I would reset expectations.", b: "If I were managing this team, I would reset expectations." },
    { f: "If this ___ a client-facing bug, we would patch it tonight.", b: "If this were a client-facing bug, we would patch it tonight." },
    { f: "If we ___ starting over, I would pick a simpler stack.", b: "If we were starting over, I would pick a simpler stack." },
    { f: "If I ___ the customer, I would want clearer pricing.", b: "If I were the customer, I would want clearer pricing." },
    { f: "If ethics ___ optional, we would lose credibility.", b: "If ethics were optional, we would lose credibility." },
    T("もし私が裁判官なら、もっと厳しく罰する。", "If I were the judge, I would impose a stricter penalty."),
    { f: "If funding ___ guaranteed, we would expand the lab.", b: "If funding were guaranteed, we would expand the lab." },
    { f: "If silence ___ agreement, we would have a problem.", b: "If silence were agreement, we would have a problem." },
    { f: "If I ___ designing this flow, I would add a confirmation step.", b: "If I were designing this flow, I would add a confirmation step." },
    { f: "If reputation ___ currency, every reply would matter.", b: "If reputation were currency, every reply would matter." },
    T("もし資源が無限なら、実験をもっと重ねられる。", "If resources were unlimited, we could run more experiments."),
    { f: "If I ___ on the board, I would ask tougher questions.", b: "If I were on the board, I would ask tougher questions." },
    { f: "If empathy ___ standard here, feedback would sting less.", b: "If empathy were standard here, feedback would sting less." },
    { f: "If speed ___ the only metric, quality would suffer.", b: "If speed were the only metric, quality would suffer." },
    { f: "If I ___ rewriting this email, I would shorten the opening.", b: "If I were rewriting this email, I would shorten the opening." },
  ]),
  deck("意見を述べる①", "Explaining opinions — I believe that…", [
    { f: "I ___ that remote work boosts productivity for many roles.", b: "I believe that remote work boosts productivity for many roles." },
    { f: "I ___ that early feedback saves money later.", b: "I believe that early feedback saves money later." },
    { f: "I ___ that everyone deserves a clear career path.", b: "I believe that everyone deserves a clear career path." },
    { f: "I ___ that small habits shape long-term health.", b: "I believe that small habits shape long-term health." },
    { f: "I ___ that transparency builds trust on teams.", b: "I believe that transparency builds trust on teams." },
    T("公平な手続きが正義だと信じている。", "I believe that fair procedures are what justice means."),
    { f: "I ___ that we should measure outcomes, not hours.", b: "I believe that we should measure outcomes, not hours." },
    { f: "I ___ that language learning takes patient practice.", b: "I believe that language learning takes patient practice." },
    { f: "I ___ that cities need greener public spaces.", b: "I believe that cities need greener public spaces." },
    { f: "I ___ that good design is invisible until it breaks.", b: "I believe that good design is invisible until it breaks." },
    T("多様性は創造性を高めると信じている。", "I believe that diversity strengthens creativity."),
    { f: "I ___ that we owe users honest release notes.", b: "I believe that we owe users honest release notes." },
    { f: "I ___ that sleep is undervalued in startup culture.", b: "I believe that sleep is undervalued in startup culture." },
    { f: "I ___ that mentors accelerate growth.", b: "I believe that mentors accelerate growth." },
    { f: "I ___ that curiosity matters more than raw talent.", b: "I believe that curiosity matters more than raw talent." },
  ]),
  deck("意見を述べる②", "Explaining opinions — framing & hedging", [
    { f: "___ my view, the benefits outweigh the risks.", b: "In my view, the benefits outweigh the risks." },
    { f: "Personally, I ___ we should delay the launch.", b: "Personally, I think we should delay the launch." },
    { f: "___ speaking, the timeline looks unrealistic.", b: "Frankly speaking, the timeline looks unrealistic." },
    { f: "___ I'm concerned about scope creep.", b: "To be honest, I'm concerned about scope creep." },
    { f: "___ the evidence suggests we should wait.", b: "From my perspective, the evidence suggests we should wait." },
    T("私の経験では、早すぎる最適化は危険だ。", "In my experience, premature optimization is risky."),
    { f: "___ I would argue that consistency beats novelty here.", b: "Broadly, I would argue that consistency beats novelty here." },
    { f: "___ it seems to me that we lack a single owner.", b: "It seems to me that we lack a single owner." },
    { f: "___ I tend to think smaller teams ship faster.", b: "I tend to think smaller teams ship faster." },
    { f: "___ I'm inclined to support the pilot project.", b: "I'm inclined to support the pilot project." },
    T("どちらかというと、慎重な方がいい。", "If anything, I'd rather be cautious."),
    { f: "___ on balance, I'd choose the safer option.", b: "On balance, I'd choose the safer option." },
    { f: "___ as I see it, communication is the bottleneck.", b: "As I see it, communication is the bottleneck." },
    { f: "___ my impression is that morale has improved.", b: "My impression is that morale has improved." },
    { f: "___ , we should pause the rollout until QA signs off.", b: "In my opinion, we should pause the rollout until QA signs off." },
  ]),
  deck("意見を述べる③", "Explaining opinions — clarity & strength", [
    { f: "My ___ position is that we need written criteria.", b: "My firm position is that we need written criteria." },
    { f: "The ___ point I'm making is that cost isn't the only factor.", b: "The key point I'm making is that cost isn't the only factor." },
    { f: "Let me ___ my reasoning in three short bullets.", b: "Let me outline my reasoning in three short bullets." },
    { f: "I want to ___ this clearly: we can't accept further delay.", b: "I want to state this clearly: we can't accept further delay." },
    { f: "To ___ my argument, consider what happened last quarter.", b: "To strengthen my argument, consider what happened last quarter." },
    T("結論として、反対せざるを得ない。", "In conclusion, I feel compelled to disagree."),
    { f: "What I'm ___ is that trust takes years to rebuild.", b: "What I'm driving at is that trust takes years to rebuild." },
    { f: "I should ___ that I don't speak for the whole department.", b: "I should stress that I don't speak for the whole department." },
    { f: "Another ___ worth highlighting is data privacy.", b: "Another angle worth highlighting is data privacy." },
    { f: "I am ___ convinced that this vendor is the right fit.", b: "I am strongly convinced that this vendor is the right fit." },
    T("簡単に言えば、今はリスクが高すぎる。", "Put simply, the risk is too high right now."),
    { f: "If I may ___, this plan ignores frontline feedback.", b: "If I may be blunt, this plan ignores frontline feedback." },
    { f: "The ___ I want to leave you with is urgency.", b: "The takeaway I want to leave you with is urgency." },
    { f: "I am ___ opposed to cutting training first.", b: "I am firmly opposed to cutting training first." },
    { f: "Let me ___ one last example from our pilot.", b: "Let me cite one last example from our pilot." },
  ]),
  deck("同意・不同意①", "Agreeing & partial agreement", [
    { f: "I ___ with you that the first draft was weak.", b: "I agree with you that the first draft was weak." },
    { f: "I ___ — the timeline does look tight.", b: "I agree — the timeline does look tight." },
    { f: "I'm ___ on board with the safety checklist idea.", b: "I'm completely on board with the safety checklist idea." },
    { f: "I ___ partly: the design is elegant, but it's hard to maintain.", b: "I agree partly: the design is elegant, but it's hard to maintain." },
    { f: "You have a ___ there about vendor lock-in.", b: "You have a point there about vendor lock-in." },
    T("その通りだと思う。特にコストの面で。", "I think you're right, especially about the cost."),
    { f: "I couldn't ___ more about the need for documentation.", b: "I couldn't agree more about the need for documentation." },
    { f: "That's a ___ observation about user fatigue.", b: "That's a fair observation about user fatigue." },
    { f: "I'm ___ to agree if we add a rollback plan.", b: "I'm willing to agree if we add a rollback plan." },
    { f: "I see ___ you're coming from on staffing.", b: "I see where you're coming from on staffing." },
    T("基本的には賛成だが、細部は詰めたい。", "I agree in principle, but I'd like to nail down the details."),
    { f: "I share your ___ about long-term sustainability.", b: "I share your concern about long-term sustainability." },
    { f: "I'm ___ with the direction, not every tactic.", b: "I'm aligned with the direction, not every tactic." },
    { f: "True, ___ we should still test edge cases.", b: "True, though we should still test edge cases." },
    { f: "I accept that ___ if we cap the budget.", b: "I accept that proposal if we cap the budget." },
  ]),
  deck("同意・不同意②", "Disagreeing & uncertainty", [
    { f: "I'm ___ sure I agree with that conclusion.", b: "I'm not sure I agree with that conclusion." },
    { f: "I see it ___ — the risk profile looks different to me.", b: "I see it differently — the risk profile looks different to me." },
    { f: "I have ___ about relying on a single supplier.", b: "I have reservations about relying on a single supplier." },
    { f: "I'd ___ to push back gently on that assumption.", b: "I'd like to push back gently on that assumption." },
    { f: "I'm ___ I can't support cutting QA hours.", b: "I'm afraid I can't support cutting QA hours." },
    T("完全には同意できない。", "I don't entirely agree with that."),
    { f: "With respect, I ___ that the data supports the claim.", b: "With respect, I don't think the data supports the claim." },
    { f: "I may be ___, but this feels rushed.", b: "I may be wrong, but this feels rushed." },
    { f: "I'm ___ on the fence until we see the prototype.", b: "I'm still on the fence until we see the prototype." },
    { f: "I wouldn't go ___ far as to call it a failure.", b: "I wouldn't go so far as to call it a failure." },
    T("その解釈には疑問がある。", "I'm skeptical of that interpretation."),
    { f: "I hear you, ___ I'm not fully convinced yet.", b: "I hear you, but I'm not fully convinced yet." },
    { f: "Could we ___ that from another angle?", b: "Could we look at that from another angle?"},
    { f: "I need more ___ before I can endorse this.", b: "I need more evidence before I can endorse this." },
    { f: "Let's agree to ___ — we'll test both hypotheses.", b: "Let's agree to disagree — we'll test both hypotheses." },
  ]),
  deck("原因と結果① because", "Cause & effect — because (complex)", [
    { f: "We postponed the release ___ several critical bugs remained.", b: "We postponed the release because several critical bugs remained." },
    { f: "Morale improved ___ managers started listening in one-on-ones.", b: "Morale improved because managers started listening in one-on-ones." },
    { f: "Sales rose ___ the campaign targeted a younger audience.", b: "Sales rose because the campaign targeted a younger audience." },
    { f: "I was late ___ a signal failure stopped the trains.", b: "I was late because a signal failure stopped the trains." },
    { f: "We chose this vendor ___ their support response time is fast.", b: "We chose this vendor because their support response time is fast." },
    T("彼は辞めた。待遇に不満があったからだ。", "He quit because he was unhappy with the compensation."),
    { f: "The event succeeded ___ volunteers coordinated every detail.", b: "The event succeeded because volunteers coordinated every detail." },
    { f: "I trust her ___ she admits mistakes quickly.", b: "I trust her because she admits mistakes quickly." },
    { f: "Traffic was awful ___ three lanes were closed for repair.", b: "Traffic was awful because three lanes were closed for repair." },
    { f: "We invested ___ we believed the market would mature.", b: "We invested because we believed the market would mature." },
    T("結果が良かったのは、準備が徹底していたからだ。", "The outcome was good because preparation was thorough."),
    { f: "I declined ___ I already committed to another project.", b: "I declined because I already committed to another project." },
    { f: "The app crashed ___ memory usage spiked unexpectedly.", b: "The app crashed because memory usage spiked unexpectedly." },
    { f: "She stayed calm ___ she had rehearsed worst-case scenarios.", b: "She stayed calm because she had rehearsed worst-case scenarios." },
    { f: "We expanded ___ customer demand exceeded forecasts.", b: "We expanded because customer demand exceeded forecasts." },
  ]),
  deck("原因と結果② therefore / as a result", "Cause & effect — therefore & as a result", [
    { f: "Costs rose sharply. ___, we froze hiring.", b: "Costs rose sharply. Therefore, we froze hiring." },
    { f: "The trial failed. ___, we pivoted to a new model.", b: "The trial failed. As a result, we pivoted to a new model." },
    { f: "Demand doubled. ___, lead times stretched.", b: "Demand doubled. Consequently, lead times stretched." },
    { f: "We missed two milestones. ___, stakeholders lost confidence.", b: "We missed two milestones. As a result, stakeholders lost confidence." },
    { f: "The policy changed. ___, we updated the handbook.", b: "The policy changed. Therefore, we updated the handbook." },
    T("品質が上がった。その結果、返品が減った。", "Quality improved. As a result, returns decreased."),
    { f: "The server overheated. ___, we added cooling fans.", b: "The server overheated. Therefore, we added cooling fans." },
    { f: "Users complained about clutter. ___, we simplified the UI.", b: "Users complained about clutter. Consequently, we simplified the UI." },
    { f: "Funding arrived early. ___, we accelerated the roadmap.", b: "Funding arrived early. As a result, we accelerated the roadmap." },
    { f: "The keynote ran long. ___, lunch started late.", b: "The keynote ran long. Therefore, lunch started late." },
    T("交渉が決裂した。その結果、訴訟になった。", "Negotiations collapsed. As a result, it went to court."),
    { f: "We lacked data. ___, the report stayed qualitative.", b: "We lacked data. Therefore, the report stayed qualitative." },
    { f: "Attendance dropped. ___, we merged two sessions.", b: "Attendance dropped. As a result, we merged two sessions." },
    { f: "The storm passed. ___, flights resumed by evening.", b: "The storm passed. Consequently, flights resumed by evening." },
    { f: "Trust eroded. ___, turnover increased.", b: "Trust eroded. As a result, turnover increased." },
  ]),
  deck("原因と結果③ つなぎ", "Cause & effect — linking chains", [
    { f: "Because we ___ early, we caught the mistake before launch.", b: "Because we tested early, we caught the mistake before launch." },
    { f: "Since the ___ was unclear, two teams duplicated work.", b: "Since the ownership was unclear, two teams duplicated work." },
    { f: "Given the ___, we recommended a phased rollout.", b: "Given the uncertainty, we recommended a phased rollout." },
    { f: "Owing to ___ cuts, the library reduced its hours.", b: "Owing to budget cuts, the library reduced its hours." },
    { f: "Due to ___ weather, the outdoor class moved online.", b: "Due to severe weather, the outdoor class moved online." },
    T("人手不足のため、営業時間を短縮した。", "Because of a staff shortage, we shortened opening hours."),
    { f: "Thanks to ___ coaching, her confidence grew.", b: "Thanks to patient coaching, her confidence grew." },
    { f: "The delay stemmed ___ a mislabeled shipment.", b: "The delay stemmed from a mislabeled shipment." },
    { f: "The outage was ___ human error, not a cyberattack.", b: "The outage was caused by human error, not a cyberattack." },
    { f: "One slip led ___ another, and the deadline slipped.", b: "One slip led to another, and the deadline slipped." },
    T("連鎖的に、コストが膨らんだ。", "Costs ballooned in a chain reaction."),
    { f: "Poor sleep contributed ___ several mistakes that week.", b: "Poor sleep contributed to several mistakes that week." },
    { f: "The spike in demand triggered ___ hiring freeze to lift.", b: "The spike in demand triggered the hiring freeze to lift." },
    { f: "A single bug cascaded ___ multiple customer complaints.", b: "A single bug cascaded into multiple customer complaints." },
    { f: "Their silence implied ___ they disagreed with the plan.", b: "Their silence implied that they disagreed with the plan." },
  ]),
  deck("体験を詳しく①", "Describing experiences — emotion", [
    { f: "I felt ___ when they announced my name.", b: "I felt overwhelmed when they announced my name." },
    { f: "I was ___ relieved once the results came back negative.", b: "I was incredibly relieved once the results came back negative." },
    { f: "The news left me ___ for days.", b: "The news left me anxious for days." },
    { f: "I was ___ proud watching my teammate present.", b: "I was genuinely proud watching my teammate present." },
    { f: "The crowd's energy made me ___ alive.", b: "The crowd's energy made me feel alive." },
    T("寂しさと安堵が入り混じった。", "I felt a mix of loneliness and relief."),
    { f: "I walked out feeling ___ about the whole process.", b: "I walked out feeling bitter about the whole process." },
    { f: "Her kindness touched me ___ than I expected.", b: "Her kindness touched me more deeply than I expected." },
    { f: "I was ___ embarrassed when I mispronounced his name.", b: "I was slightly embarrassed when I mispronounced his name." },
    { f: "The silence in the room felt ___ .", b: "The silence in the room felt awkward." },
    T("達成感で胸がいっぱいだった。", "I felt a huge sense of accomplishment."),
    { f: "I stayed calm, ___ I was shaking inside.", b: "I stayed calm, though I was shaking inside." },
    { f: "The ending moved me ___ I cried in the theater.", b: "The ending moved me so much that I cried in the theater." },
    { f: "I felt ___ out after three weeks of night shifts.", b: "I felt burned out after three weeks of night shifts." },
    { f: "Hearing their laughter made the trip ___ worthwhile.", b: "Hearing their laughter made the trip feel worthwhile." },
  ]),
  deck("体験を詳しく②", "Describing experiences — detail & reflection", [
    { f: "The alley smelled ___ rain and fried garlic.", b: "The alley smelled of rain and fried garlic." },
    { f: "We heard distant ___ until midnight.", b: "We heard distant drums until midnight." },
    { f: "Sunlight hit the water ___ it looked like glass.", b: "Sunlight hit the water so that it looked like glass." },
    { f: "I remember how ___ the stone steps felt under my shoes.", b: "I remember how uneven the stone steps felt under my shoes." },
    { f: "Looking back, I ___ how naive I was.", b: "Looking back, I realize how naive I was." },
    T("あの瞬間、時間が止まったように感じた。", "In that moment, it felt as if time had stopped."),
    { f: "What stuck ___ me was the guide's patience.", b: "What stuck with me was the guide's patience." },
    { f: "In hindsight, we ___ have booked earlier.", b: "In hindsight, we should have booked earlier." },
    { f: "The market was ___ that we could barely move.", b: "The market was so crowded that we could barely move." },
    { f: "I noticed ___ detail: every window was a different color.", b: "I noticed a strange detail: every window was a different color." },
    T("写真では伝わらない空気があった。", "There was an atmosphere that photos couldn't capture."),
    { f: "We stayed long enough ___ the lights dimmed.", b: "We stayed long enough to watch the lights dim." },
    { f: "The hike was harder ___ we imagined.", b: "The hike was harder than we imagined." },
    { f: "I can still ___ the taste of that soup.", b: "I can still recall the taste of that soup." },
    { f: "That trip changed ___ I think about travel.", b: "That trip changed how I think about travel." },
  ]),
  deck("ディベート①", "Debate basics — pros and cons", [
    { f: "On the ___ hand, remote work saves commute time.", b: "On the one hand, remote work saves commute time." },
    { f: "On the ___ hand, collaboration can suffer.", b: "On the other hand, collaboration can suffer." },
    { f: "One ___ is lower office rent.", b: "One advantage is lower office rent." },
    { f: "One ___ is weaker team bonding.", b: "One drawback is weaker team bonding." },
    { f: "Let's ___ the pros and cons before we decide.", b: "Let's weigh the pros and cons before we decide." },
    T("賛成派と反対派の両方を聞こう。", "Let's hear both sides of the argument."),
    { f: "A ___ argument for the merger is scale.", b: "A strong argument for the merger is scale." },
    { f: "A ___ argument against it is cultural clash.", b: "A common argument against it is cultural clash." },
    { f: "We should ___ counterarguments in the appendix.", b: "We should list counterarguments in the appendix." },
    { f: "I'm playing ___ advocate for a moment.", b: "I'm playing devil's advocate for a moment." },
    T("反対意見も真剣に検討すべきだ。", "We should take opposing views seriously."),
    { f: "The trade-off ___ speed versus quality is real.", b: "The trade-off between speed versus quality is real." },
    { f: "If we ___ only upside, we'll be blindsided.", b: "If we consider only upside, we'll be blindsided." },
    { f: "Let's ___ the discussion to three key risks.", b: "Let's narrow the discussion to three key risks." },
    { f: "We need a ___ summary for leadership.", b: "We need a balanced summary for leadership." },
  ]),
  deck("ディベート②", "Debate — weighing & rebuttal", [
    { f: "That objection ___ some weight, but it isn't decisive.", b: "That objection carries some weight, but it isn't decisive." },
    { f: "I grant you that ___, yet the trend still worries me.", b: "I grant you that profits rose, yet the trend still worries me." },
    { f: "Even if we accept ___, the conclusion doesn't follow.", b: "Even if we accept their premise, the conclusion doesn't follow." },
    { f: "That rebuttal ___ the weakest part of their case.", b: "That rebuttal targets the weakest part of their case." },
    { f: "We should ___ their assumptions, not just their conclusions.", b: "We should challenge their assumptions, not just their conclusions." },
    T("データの解釈が争点だ。", "The dispute is over how to interpret the data."),
    { f: "Their analogy ___ because the contexts differ.", b: "Their analogy breaks down because the contexts differ." },
    { f: "I'd ___ that with data from our own pilot.", b: "I'd counter that with data from our own pilot." },
    { f: "Let's not ___ the ethical dimension.", b: "Let's not overlook the ethical dimension." },
    { f: "The burden of ___ should be on whoever proposes change.", b: "The burden of proof should be on whoever proposes change." },
    T("感情的な論点に逃げないでほしい。", "Please don't retreat into emotional arguments."),
    { f: "We can ___ their claim without attacking them personally.", b: "We can refute their claim without attacking them personally." },
    { f: "A cooler ___ would be to run a controlled experiment.", b: "A cooler response would be to run a controlled experiment." },
    { f: "Let's ___ where we agree before we fight over details.", b: "Let's map where we agree before we fight over details." },
    { f: "I'm trying to ___ the strongest version of their view.", b: "I'm trying to steelman the strongest version of their view." },
  ]),
  deck("職場① アイデア提示", "Workplace — presenting ideas", [
    { f: "I'd ___ to frame the problem in three layers.", b: "I'd like to frame the problem in three layers." },
    { f: "___ I'd suggest we pilot this in one region first.", b: "Broadly, I'd suggest we pilot this in one region first." },
    { f: "The ___ I'd like to make is about scalability.", b: "The core point I'd like to make is about scalability." },
    { f: "Let me ___ this with a simple diagram.", b: "Let me illustrate this with a simple diagram." },
    { f: "If we ___ the question, we avoid scope creep.", b: "If we narrow the question, we avoid scope creep." },
    T("結論から言うと、今は投資の時だ。", "Bottom line: now is the time to invest."),
    { f: "I'd ___ the floor to our analyst for the numbers.", b: "I'd yield the floor to our analyst for the numbers." },
    { f: "Could I get two ___ on this slide?", b: "Could I get two minutes on this slide?" },
    { f: "I'll ___ my case in four bullets.", b: "I'll state my case in four bullets." },
    { f: "What I'm ___ is a phased rollout, not a big bang.", b: "What I'm proposing is a phased rollout, not a big bang." },
    T("前提を共有してもいいですか。", "May I share a few assumptions up front?"),
    { f: "Let me ___ why this matters to finance.", b: "Let me spell out why this matters to finance." },
    { f: "I'd welcome ___ on whether this timeline is sane.", b: "I'd welcome pushback on whether this timeline is sane." },
    { f: "To ___ expectations, this won't fix everything overnight.", b: "To set expectations, this won't fix everything overnight." },
    { f: "I'll close ___ a single ask of the leadership team.", b: "I'll close with a single ask of the leadership team." },
  ]),
  deck("職場② 発表のつなぎ", "Workplace — signposting a talk", [
    { f: "___ I'll outline the background.", b: "First, I'll outline the background." },
    { f: "___ I'll walk through the methodology.", b: "Next, I'll walk through the methodology." },
    { f: "___ I'll share results and limitations.", b: "Then I'll share results and limitations." },
    { f: "___ I'll open the floor for questions.", b: "Finally, I'll open the floor for questions." },
    { f: "___ another angle, consider the regulatory view.", b: "From another angle, consider the regulatory view." },
    T("話を戻すが、先ほどの数字についてだ。", "To return to an earlier point about those figures."),
    { f: "___ deeper, the root cause is coordination.", b: "Digging deeper, the root cause is coordination." },
    { f: "___ briefly, we underestimated integration work.", b: "To recap briefly, we underestimated integration work." },
    { f: "___ forward, we will publish weekly metrics.", b: "Going forward, we will publish weekly metrics." },
    { f: "___ contrast, last year's curve was flat.", b: "By contrast, last year's curve was flat." },
    T("具体例を一つ挙げると…", "To give one concrete example…"),
    { f: "___ aside, the culture fit looks strong.", b: "Joking aside, the culture fit looks strong." },
    { f: "___ up, three teams need clearer owners.", b: "Wrapping up, three teams need clearer owners." },
    { f: "___ the interest of time, I'll skip the appendix.", b: "In the interest of time, I'll skip the appendix." },
    { f: "___ the record, I support the recommendation.", b: "For the record, I support the recommendation." },
  ]),
  deck("職場③ アップデート", "Workplace — giving updates (1)", [
    { f: "Quick ___ : we shipped the hotfix last night.", b: "Quick update: we shipped the hotfix last night." },
    { f: "We're ___ track to finish the redesign by Friday.", b: "We're on track to finish the redesign by Friday." },
    { f: "We're slightly ___ because of a vendor delay.", b: "We're slightly behind because of a vendor delay." },
    { f: "No ___ this week — same blockers as last week.", b: "No major changes this week — same blockers as last week." },
    { f: "Risk ___ : medium, mainly integration.", b: "Risk level: medium, mainly integration." },
    T("進捗は順調だが、人手が足りない。", "Progress is good, but we're short on people."),
    { f: "I'll ___ the dashboard link after this call.", b: "I'll paste the dashboard link after this call." },
    { f: "Next ___ : finalize copy and run A/B tests.", b: "Next steps: finalize copy and run A/B tests." },
    { f: "ETA for the beta is ___, barring surprises.", b: "ETA for the beta is March 3, barring surprises." },
    { f: "We ___ a dependency on the legal review.", b: "We hit a dependency on the legal review." },
    T("顧客からのフィードバックをまとめた。", "I've summarized feedback from customers."),
    { f: "I'll ___ the team by email with the new timeline.", b: "I'll brief the team by email with the new timeline." },
    { f: "Nothing ___ to report on security incidents.", b: "Nothing new to report on security incidents." },
    { f: "We're green ___ performance; yellow on staffing.", b: "We're green on performance; yellow on staffing." },
    { f: "I'll ___ a written summary to the channel.", b: "I'll post a written summary to the channel." },
  ]),
  deck("職場④ アップデート②", "Workplace — giving updates (2)", [
    { f: "Since we last met, we ___ two critical bugs.", b: "Since we last met, we closed two critical bugs." },
    { f: "We ___ scope slightly to protect the deadline.", b: "We reduced scope slightly to protect the deadline." },
    { f: "Adoption is up ___ week over week.", b: "Adoption is up 8% week over week." },
    { f: "Churn ticked ___ after the price change.", b: "Churn ticked upward after the price change." },
    { f: "We ___ a hiring freeze until Q3.", b: "We instituted a hiring freeze until Q3." },
    T("予算は計画の92%まで消化した。", "We've used 92% of the planned budget."),
    { f: "Partnerships: one LOI ___, two in negotiation.", b: "Partnerships: one LOI signed, two in negotiation." },
    { f: "I'll ___ a risk register by EOD.", b: "I'll circulate a risk register by EOD." },
    { f: "We need a ___ on the API outage root cause.", b: "We need a decision on the API outage root cause." },
    { f: "Support backlog ___ from 40 to 22 tickets.", b: "Support backlog dropped from 40 to 22 tickets." },
    T("来週はデモとレビューに集中する。", "Next week we'll focus on demos and reviews."),
    { f: "I'll ___ stakeholders once finance signs off.", b: "I'll notify stakeholders once finance signs off." },
    { f: "We ___ the launch by one sprint to harden security.", b: "We delayed the launch by one sprint to harden security." },
    { f: "Quality metrics are ___ except for mobile Safari.", b: "Quality metrics are stable except for mobile Safari." },
    { f: "I'll ___ a live demo in tomorrow's stand-up.", b: "I'll schedule a live demo in tomorrow's stand-up." },
  ]),
  deck("問題の議論①", "Problem discussion — identifying issues", [
    { f: "The ___ issue is inconsistent handoffs between teams.", b: "The core issue is inconsistent handoffs between teams." },
    { f: "We're seeing a ___ in communication after the reorg.", b: "We're seeing a pattern in communication after the reorg." },
    { f: "The ___ cause looks like a race condition.", b: "The probable cause looks like a race condition." },
    { f: "Symptoms ___ slow sync and duplicate records.", b: "Symptoms include slow sync and duplicate records." },
    { f: "We should ___ whether incentives are misaligned.", b: "We should examine whether incentives are misaligned." },
    T("根本原因はプロセスの欠陥だと思う。", "I think the root cause is a flawed process."),
    { f: "Let's ___ the problem statement before we brainstorm fixes.", b: "Let's align on the problem statement before we brainstorm fixes." },
    { f: "The pain ___ mostly affects enterprise customers.", b: "The pain point mostly affects enterprise customers." },
    { f: "We lack ___ visibility into partner SLAs.", b: "We lack clear visibility into partner SLAs." },
    { f: "This isn't a one-off; it's a ___ failure.", b: "This isn't a one-off; it's a systemic failure." },
    T("リスクを過小評価してきた。", "We've been underestimating the risk."),
    { f: "The bottleneck ___ between design and engineering.", b: "The bottleneck sits between design and engineering." },
    { f: "We should ___ how often this error reproduces.", b: "We should quantify how often this error reproduces." },
    { f: "Stakeholders ___ frustrated with opaque status updates.", b: "Stakeholders feel frustrated with opaque status updates." },
    { f: "Let's ___ the scope of 'done' for this milestone.", b: "Let's define the scope of 'done' for this milestone." },
  ]),
  deck("問題の議論②", "Problem discussion — solutions", [
    { f: "One option ___ to split the monolith gradually.", b: "One option is to split the monolith gradually." },
    { f: "We could ___ a rotating on-call roster.", b: "We could pilot a rotating on-call roster." },
    { f: "I recommend we ___ a single source of truth for specs.", b: "I recommend we establish a single source of truth for specs." },
    { f: "Let's ___ owners for each workstream by Friday.", b: "Let's assign owners for each workstream by Friday." },
    { f: "We should ___ a blameless postmortem next week.", b: "We should schedule a blameless postmortem next week." },
    T("短期的にはワークラウンドを、中長期では修正を。", "Short term: a workaround; long term: a proper fix."),
    { f: "Mitigation ___ include rate limits and caching.", b: "Mitigation could include rate limits and caching." },
    { f: "We might ___ external auditors if trust is low.", b: "We might bring in external auditors if trust is low." },
    { f: "Let's ___ a rollback plan before we flip the flag.", b: "Let's document a rollback plan before we flip the flag." },
    { f: "I'd ___ weekly syncs until the metrics stabilize.", b: "I'd propose weekly syncs until the metrics stabilize." },
    T("成功指標を合意してから進めよう。", "Let's agree on success metrics before we proceed."),
    { f: "We should ___ user research before redesigning checkout.", b: "We should fund user research before redesigning checkout." },
    { f: "A quick win ___ to fix the broken signup link.", b: "A quick win is to fix the broken signup link." },
    { f: "Longer term, we should ___ toward modular services.", b: "Longer term, we should migrate toward modular services." },
    { f: "Let's ___ progress against these three KPIs.", b: "Let's track progress against these three KPIs." },
  ]),
  deck("文化・社会①", "Cultural & social topics (1)", [
    { f: "___ cultures, direct feedback can sound rude.", b: "Across cultures, direct feedback can sound rude." },
    { f: "In some places, ___ late is more acceptable than elsewhere.", b: "In some places, arriving late is more acceptable than elsewhere." },
    { f: "Food rituals often ___ family bonds.", b: "Food rituals often reflect family bonds." },
    { f: "___ habits like bowing or handshakes carry social meaning.", b: "Small habits like bowing or handshakes carry social meaning." },
    { f: "Lifestyle ___ in cities versus countryside are widening.", b: "Lifestyle gaps in cities versus countryside are widening." },
    T("宗教的な配慮を忘れないでほしい。", "Please remember to respect religious considerations."),
    { f: "Public ___ expectations differ from private norms.", b: "Public behavior expectations differ from private norms." },
    { f: "Gift-giving rules can ___ surprisingly formal.", b: "Gift-giving rules can feel surprisingly formal." },
    { f: "___ media shapes how teens see body image.", b: "Social media shapes how teens see body image." },
    { f: "Work-life ___ means different things in different countries.", b: "Work-life balance means different things in different countries." },
    T("「個人主義」は単純化しすぎだ。", "Calling it individualism is an oversimplification."),
    { f: "Festivals reveal ___ values a community celebrates.", b: "Festivals reveal which values a community celebrates." },
    { f: "Immigration debates often ___ fears about identity.", b: "Immigration debates often touch fears about identity." },
    { f: "___ etiquette around shoes indoors trips visitors up.", b: "Simple etiquette around shoes indoors trips visitors up." },
    { f: "Cultural ___ isn't the same as stereotyping.", b: "Cultural awareness isn't the same as stereotyping." },
  ]),
  deck("文化・社会②", "Cultural & social topics (2)", [
    { f: "___ abroad taught me to question my defaults.", b: "Living abroad taught me to question my defaults." },
    { f: "I learned not to ___ silence as agreement.", b: "I learned not to read silence as agreement." },
    { f: "Humor doesn't always ___ borders cleanly.", b: "Humor doesn't always translate across borders cleanly." },
    { f: "Different generations ___ privacy online differently.", b: "Different generations view privacy online differently." },
    { f: "School lunches ___ class and health inequalities.", b: "School lunches mirror class and health inequalities." },
    T("外食文化は都市と地方で違う。", "Eating-out culture differs between urban and rural areas."),
    { f: "___ norms around tipping confuse many travelers.", b: "Unwritten norms around tipping confuse many travelers." },
    { f: "Public ___ varies widely on trains between countries.", b: "Public etiquette varies widely on trains between countries." },
    { f: "___ identity can feel fluid in multicultural cities.", b: "Cultural identity can feel fluid in multicultural cities." },
    { f: "Holidays ___ how a society marks time and loss.", b: "Holidays reveal how a society marks time and loss." },
    T("偏見を減らすには対話が必要だ。", "Dialogue is needed to reduce prejudice."),
    { f: "___ curiosity beats snap judgments about strangers.", b: "Honest curiosity beats snap judgments about strangers." },
    { f: "Some ___ prefer consensus before a public decision.", b: "Some cultures prefer consensus before a public decision." },
    { f: "___ media literacy is now a civic skill.", b: "Basic media literacy is now a civic skill." },
    { f: "___ listening helps more than giving quick advice.", b: "Patient listening helps more than giving quick advice." },
  ]),
  deck("叙述①", "Narrative skills — longer stories (1)", [
    { f: "It started ___ a misunderstanding about the deadline.", b: "It started with a misunderstanding about the deadline." },
    { f: "___ morning, everything still felt normal.", b: "That morning, everything still felt normal." },
    { f: "___ noon, rumors had spread across the office.", b: "By noon, rumors had spread across the office." },
    { f: "___ evening, leadership called an emergency meeting.", b: "By evening, leadership called an emergency meeting." },
    { f: "___ the end of the week, we had a new plan.", b: "By the end of the week, we had a new plan." },
    T("振り返ると、あの一言が転機だった。", "In hindsight, that one sentence was the turning point."),
    { f: "___ the crisis, the team actually grew closer.", b: "During the crisis, the team actually grew closer." },
    { f: "___ a while, I wasn't sure we'd recover.", b: "For a while, I wasn't sure we'd recover." },
    { f: "___ then, we've documented every decision.", b: "Since then, we've documented every decision." },
    { f: "___ story matters because trust was on the line.", b: "The story matters because trust was on the line." },
    T("クライマックスは金曜の夜の会議だった。", "The climax was the meeting on Friday night."),
    { f: "___ back, I'd call it a painful lesson.", b: "Looking back, I'd call it a painful lesson." },
    { f: "The ___: two people resigned anyway.", b: "The epilogue: two people resigned anyway." },
    { f: "___ the narrator, I still wonder what we missed.", b: "As the narrator, I still wonder what we missed." },
    { f: "___ tension built slowly, then broke all at once.", b: "The tension built slowly, then broke all at once." },
  ]),
  deck("叙述②", "Narrative skills — longer stories (2)", [
    { f: "___ set the scene: it was raining in Osaka.", b: "Let me set the scene: it was raining in Osaka." },
    { f: "___ character who mattered most was the quiet intern.", b: "The character who mattered most was the quiet intern." },
    { f: "___ subplot involved a missing expense receipt.", b: "A subplot involved a missing expense receipt." },
    { f: "___ turning point came when she spoke up.", b: "The turning point came when she spoke up." },
    { f: "___ falling action, we renegotiated the contract.", b: "During the falling action, we renegotiated the contract." },
    T("結末は bittersweet だった。", "The ending was bittersweet."),
    { f: "___ on it, I should have asked more questions sooner.", b: "Reflecting on it, I should have asked more questions sooner." },
    { f: "___ pace quickened once the investors arrived.", b: "The pace quickened once the investors arrived." },
    { f: "___ flashback explains why he distrusts banks.", b: "A short flashback explains why he distrusts banks." },
    { f: "___ foreshadowing was subtle, but it was there.", b: "The foreshadowing was subtle, but it was there." },
    T("聞き手を飽きさせないには？", "How do we keep the listener engaged?"),
    { f: "___ hook I used was a single surprising statistic.", b: "The hook I used was a single surprising statistic." },
    { f: "___ resolution wasn't perfect, but it was honest.", b: "The resolution wasn't perfect, but it was honest." },
    { f: "___ coda: we still send that intern holiday cards.", b: "The coda: we still send that intern holiday cards." },
    { f: "___ throughline was integrity, not profit.", b: "The throughline was integrity, not profit." },
  ]),
  deck("明確化の戦略", "Clarification strategies", [
    { f: "___ do you mean by 'soon' — this week or this month?", b: "What do you mean by 'soon' — this week or this month?" },
    { f: "Could you ___ that in simpler terms?", b: "Could you explain that in simpler terms?" },
    { f: "Let me ___ what I meant — I wasn't blaming you.", b: "Let me clarify what I meant — I wasn't blaming you." },
    { f: "I want to make sure we're ___ about the same metric.", b: "I want to make sure we're talking about the same metric." },
    { f: "When you say 'stable,' do you ___ uptime or error rate?", b: "When you say 'stable,' do you mean uptime or error rate?" },
    T("言い換えると、コスト削減が目的か？", "In other words, is the goal to cut costs?"),
    { f: "Sorry, I ___ you — could you repeat the last sentence?", b: "Sorry, I lost you — could you repeat the last sentence?" },
    { f: "Can we ___ an example so I'm sure I follow?", b: "Can we walk through an example so I'm sure I follow?" },
    { f: "I'm not ___ I understand the trade-offs yet.", b: "I'm not sure I understand the trade-offs yet." },
    { f: "Just to ___, you're proposing we skip QA?", b: "Just to confirm, you're proposing we skip QA?" },
    T("要点を三行でまとめてもらえる？", "Could you summarize the gist in three lines?"),
    { f: "Let me ___ my point another way.", b: "Let me restate my point another way." },
    { f: "Which part feels ___ to you?", b: "Which part feels unclear to you?" },
    { f: "I'll ___ my screen so we can annotate together.", b: "I'll share my screen so we can annotate together." },
    { f: "Before we move on, ___ we align on definitions?", b: "Before we move on, can we align on definitions?" },
  ]),
];

function build() {
  if (SPECS.length < 30 || SPECS.length > 35) {
    throw new Error(`Expected 30–35 decks, got ${SPECS.length}`);
  }
  const total = SPECS.reduce((s, d) => s + d.cards.length, 0);
  const expectedTotal = SPECS.length * N;
  if (total !== expectedTotal) {
    throw new Error(`Expected ${expectedTotal} cards (${SPECS.length}×${N}), got ${total}`);
  }
  if (total < 400 || total > 500) {
    throw new Error(`Expected 400–500 total cards, got ${total}`);
  }

  const decks = SPECS.map((spec, di) => ({
    id: `study-i3-deck-${di}`,
    titleJa: spec.titleJa,
    titleEn: spec.titleEn,
    sortOrder: di,
    cards: spec.cards.map(([frontJa, backEn], ci) => ({
      id: `study-i3-d${di}-c${ci}`,
      frontJa,
      backEn,
      sortOrder: ci,
      exercise: inferReorderExerciseFromBlankPrompt(
        frontJa,
        backEn,
        `study-i3-d${di}-c${ci}`,
      ) ?? undefined,
    })),
  }));

  const assessment = {
    passingScore: 72,
    items: [
      {
        id: "study-i3-a0",
        promptJa: "「Although it was late, we stayed.」に近い文法は？",
        promptEn: "Which sentence uses although correctly?",
        options: [
          "Although it was late, we stayed.",
          "Although it was late, but we stayed.",
          "It was although late, we stayed.",
          "Although late was it, we stayed.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a1",
        promptJa: "第二条件として自然なのは？",
        promptEn: "Which is a natural second conditional?",
        options: [
          "If I have time, I would travel.",
          "If I had time, I would travel.",
          "If I had time, I will travel.",
          "If I have time, I had traveled.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i3-a2",
        promptJa: "丁寧に反対を示す表現は？",
        promptEn: "Which politely signals disagreement?",
        options: [
          "You're completely wrong.",
          "I'm not sure I agree with that conclusion.",
          "Nobody agrees with you.",
          "That is stupid idea.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i3-a3",
        promptJa: "原因と結果のつなぎとして自然なのは？",
        promptEn: "Which links cause and result naturally?",
        options: [
          "It rained. Therefore, we canceled the picnic.",
          "It rained. Because, we canceled the picnic.",
          "It rained. Although, we canceled the picnic.",
          "It rained. While, we canceled the picnic.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a4",
        promptJa: "意見を述べる導入として自然なのは？",
        promptEn: "Which opens an opinion clearly?",
        options: [
          "I believe that transparency builds trust.",
          "I believing that transparency builds trust.",
          "Believe I that transparency builds trust.",
          "I believe transparency that builds trust.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a5",
        promptJa: "ディベートで両面を示す表現は？",
        promptEn: "Which phrase presents both sides?",
        options: [
          "Only one hand.",
          "On the one hand … on the other hand …",
          "On the one side … on the same side …",
          "One hand other hand no.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i3-a6",
        promptJa: "アップデートの書き出しとして自然なのは？",
        promptEn: "Which is a natural update opener?",
        options: [
          "Quick update: we shipped the hotfix last night.",
          "Quickly updating: ship hotfix night.",
          "Update quick we ship hotfix.",
          "Hotfix shipped quick update.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a7",
        promptJa: "意味を確認する表現は？",
        promptEn: "Which asks for clarification?",
        options: [
          "What do you mean by that term?",
          "What you mean is?",
          "Mean what you?",
          "You mean what term?",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a8",
        promptJa: "「Let me clarify…」に最も近いのは？",
        promptEn: "Which is closest to “Let me clarify…”?",
        options: [
          "Let me confuse what I meant.",
          "Let me clarify what I meant.",
          "Let me clarifyment my meant.",
          "Clarify let me not.",
        ],
        correctIndex: 1,
      },
      {
        id: "study-i3-a9",
        promptJa: "while（対比）として自然なのは？",
        promptEn: "Which uses while for contrast?",
        options: [
          "While I respect his work, I disagree with this decision.",
          "While I respecting his work, I disagree.",
          "While respect I his work, disagree.",
          "While I respect his work, but I disagree.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a10",
        promptJa: "叙述で場面を置く表現は？",
        promptEn: "Which sets the scene in a story?",
        options: [
          "Let me set the scene: it was raining in Osaka.",
          "Set me let scene raining Osaka.",
          "Scene set let raining me.",
          "Let scene me set Osaka raining.",
        ],
        correctIndex: 0,
      },
      {
        id: "study-i3-a11",
        promptJa: "文化的配慮を示す表現として自然なのは？",
        promptEn: "Which shows cultural awareness?",
        options: [
          "Everyone thinks the same everywhere.",
          "Across cultures, direct feedback can sound rude.",
          "Cultures no difference feedback.",
          "Across culture feedback rude always.",
        ],
        correctIndex: 1,
      },
    ],
  };

  const doc = { version: 1 as const, levelCode: "INTERMEDIATE_3" as const, decks, assessment };
  const parsed = intermediate3LevelFileSchema.safeParse(doc);
  if (!parsed.success) {
    console.error(parsed.error.flatten());
    throw new Error("intermediate3LevelFileSchema validation failed");
  }
  fs.writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`, "utf8");
  console.log(`Wrote ${OUT} (${decks.length} decks, ${total} cards)`);
}

build();
