/**
 * Build data/study/beginner-3.json — Beginner L3 (simple independence).
 * Spec: 20–25 decks, 12–14 cards each, 250–300 total. JP prompts taper per `prompt-locale-policy.ts`.
 *
 *   yarn study:build-beginner3-json   (repo root or apps/web)
 */
import fs from "node:fs";
import path from "node:path";
import { StudyLevelCode } from "../src/generated/prisma/client";
import { beginner3LevelFileSchema } from "../src/lib/study/schemas";

const OUT = path.join(__dirname, "../data/study/beginner-3.json");

type Pair = [string, string];

const DECKS: { titleJa: string; titleEn: string; cards: Pair[] }[] = [
  {
    titleJa: "過去形（基本）— went / ate / saw",
    titleEn: "Past Tense — went / ate / saw",
    cards: [
      ["昨日、学校に行った。", "I went to school yesterday."],
      ["朝ご飯にパンを食べた。", "I ate bread for breakfast."],
      ["映画を見た。", "I saw a movie."],
      ["友達に会った。", "I met a friend."],
      ["宿題をした。", "I did my homework."],
      ["駅まで歩いた。", "I walked to the station."],
      ["たくさん寝た。", "I slept a lot."],
      ["コーヒーを飲んだ。", "I drank coffee."],
      ["買い物に行った。", "I went shopping."],
      ["写真を撮った。", "I took a photo."],
      ["手紙を書いた。", "I wrote a letter."],
      ["本を読んだ。", "I read a book."],
      ["遅刻した。", "I was late."],
    ],
  },
  {
    titleJa: "過去形 — 規則動詞（-ed）",
    titleEn: "Past Tense — Regular Verbs (-ed)",
    cards: [
      ["テレビを見た。", "I watched TV."],
      ["掃除をした。", "I cleaned."],
      ["料理をした。", "I cooked."],
      ["電話をかけた。", "I called."],
      ["待った。", "I waited."],
      ["笑った。", "I laughed."],
      ["練習した。", "I practiced."],
      ["質問した。", "I asked a question."],
      ["約束した。", "I promised."],
      ["予約した。", "I made a reservation."],
      ["返事をした。", "I replied."],
      ["説明した。", "I explained."],
      ["謝った。", "I apologized."],
    ],
  },
  {
    titleJa: "過去形 — 疑問文と否定",
    titleEn: "Past Tense — Questions & Negatives",
    cards: [
      ["昨日、仕事に行きましたか？", "Did you go to work yesterday?"],
      ["彼は来なかった。", "He didn't come."],
      ["何を食べましたか？", "What did you eat?"],
      ["どこに行ったの？", "Where did you go?"],
      ["いつ始まった？", "When did it start?"],
      ["見なかった。", "I didn't see it."],
      ["聞こえなかった。", "I didn't hear it."],
      ["知らなかった。", "I didn't know."],
      ["買わなかった。", "I didn't buy it."],
      ["話さなかった。", "I didn't speak."],
      ["彼女は来ましたか？", "Did she come?"],
      ["彼らは泳いだ？", "Did they swim?"],
      ["雨は降った？", "Did it rain?"],
    ],
  },
  {
    titleJa: "未来 — be going to（形）",
    titleEn: "Future — be going to (forms)",
    cards: [
      ["旅行するつもりだ。", "I'm going to travel."],
      ["勉強するつもりだ。", "I'm going to study."],
      ["寝るつもりだ。", "I'm going to sleep."],
      ["彼は買うつもりだ。", "He's going to buy it."],
      ["私たちは行くつもりだ。", "We're going to go."],
      ["彼女は電話するつもりだ。", "She's going to call."],
      ["映画を見るつもりだ。", "I'm going to watch a movie."],
      ["料理するつもりだ。", "I'm going to cook."],
      ["走るつもりだ。", "I'm going to run."],
      ["手伝うつもりだ。", "I'm going to help."],
      ["始めるつもりだ。", "I'm going to start."],
      ["止めるつもりだ。", "I'm going to stop."],
      ["続けるつもりだ。", "I'm going to continue."],
    ],
  },
  {
    titleJa: "未来 — 予定とプラン",
    titleEn: "Future — Plans & Intentions",
    cards: [
      ["来週、京都に行くつもりだ。", "I'm going to go to Kyoto next week."],
      ["今夜、友達に会うつもりだ。", "I'm going to meet a friend tonight."],
      ["週末は休むつもりだ。", "I'm going to rest on the weekend."],
      ["新しい仕事を探すつもりだ。", "I'm going to look for a new job."],
      ["英語をもっと練習するつもりだ。", "I'm going to practice English more."],
      ["早く起きるつもりだ。", "I'm going to wake up early."],
      ["水をたくさん飲むつもりだ。", "I'm going to drink a lot of water."],
      ["毎日歩くつもりだ。", "I'm going to walk every day."],
      ["メールを返すつもりだ。", "I'm going to reply to the email."],
      ["部屋を片付けるつもりだ。", "I'm going to tidy my room."],
      ["写真を送るつもりだ。", "I'm going to send a photo."],
      ["レストランを予約するつもりだ。", "I'm going to book a restaurant."],
      ["空港に早く着くつもりだ。", "I'm going to arrive at the airport early."],
    ],
  },
  {
    titleJa: "理由の文 — because",
    titleEn: "Complex Sentences — because",
    cards: [
      ["コーヒーが好きだ。おいしいからだ。", "I like coffee because it is good."],
      ["疲れた。今日はたくさん働いたからだ。", "I'm tired because I worked a lot today."],
      ["忙しい。会議があるから行けない。", "I'm busy because I have a meeting."],
      ["寒い。冬だからだ。", "It's cold because it's winter."],
      ["お腹が空いた。昼を抜いたからだ。", "I'm hungry because I skipped lunch."],
      ["遅れた。バスに乗り遅れたからだ。", "I was late because I missed the bus."],
      ["安かった。だから買った。", "I bought it because it was cheap."],
      ["面白い。だからおすすめする。", "I recommend it because it's interesting."],
      ["難しい。だから時間がかかる。", "It takes time because it's difficult."],
      ["雨だった。だから傘を持った。", "I brought an umbrella because it was raining."],
      ["眠い。よく眠れなかったからだ。", "I'm sleepy because I didn't sleep well."],
      ["初心者だ。だからゆっくり話してほしい。", "I'm a beginner, so please speak slowly."],
      ["初めてだ。だから緊張する。", "I'm nervous because it's my first time."],
    ],
  },
  {
    titleJa: "もっと複雑な文 — like / want / need",
    titleEn: "More Complex Patterns — like / want / need",
    cards: [
      ["泳ぎ方を知りたい。", "I want to know how to swim."],
      ["ここに座ってもいい？", "Can I sit here?"],
      ["手伝ってほしい。", "I need you to help me."],
      ["静かにしてほしい。", "I need you to be quiet."],
      ["もう一度言ってほしい。", "I need you to say it again."],
      ["日本に行きたい。", "I want to go to Japan."],
      ["英語が上手になりたい。", "I want to get better at English."],
      ["この本が気に入った。", "I liked this book."],
      ["その映画を見たい。", "I want to see that movie."],
      ["水が必要だ。", "I need water."],
      ["休憩が必要だ。", "I need a break."],
      ["答えを知りたい。", "I want to know the answer."],
      ["説明してほしい。", "I want you to explain it."],
    ],
  },
  {
    titleJa: "頻度 — always / sometimes / never",
    titleEn: "Frequency — always / sometimes / never",
    cards: [
      ["いつも朝コーヒーを飲む。", "I always drink coffee in the morning."],
      ["ときどきジムに行く。", "I sometimes go to the gym."],
      ["決して嘘をつかない。", "I never tell lies."],
      ["よく本を読む。", "I often read books."],
      ["めったに遅刻しない。", "I'm rarely late."],
      ["たいてい自宅で食べる。", "I usually eat at home."],
      ["週に一度泳ぐ。", "I swim once a week."],
      ["毎日英語を勉強する。", "I study English every day."],
      ["時々外食する。", "I eat out sometimes."],
      ["彼はいつも笑顔だ。", "He always smiles."],
      ["彼女はめったに怒らない。", "She rarely gets angry."],
      ["私たちはよく散歩する。", "We often take a walk."],
      ["彼らは決して諦めない。", "They never give up."],
    ],
  },
  {
    titleJa: "比較 — bigger / better / faster",
    titleEn: "Comparisons — -er adjectives",
    cards: [
      ["この方が大きい。", "This one is bigger."],
      ["この方がいい。", "This one is better."],
      ["彼の方が速い。", "He is faster."],
      ["今日は昨日より暖かい。", "Today is warmer than yesterday."],
      ["この道の方が近い。", "This way is closer."],
      ["新しい方が高い。", "The new one is more expensive."],
      ["このケーキの方が甘い。", "This cake is sweeter."],
      ["彼女の方が上手だ。", "She is better at it."],
      ["朝の方が静かだ。", "The morning is quieter."],
      ["電車の方が速い。", "The train is faster."],
      ["この席の方が快適だ。", "This seat is more comfortable."],
      ["冬の方が寒い。", "Winter is colder."],
      ["この問題の方が簡単だ。", "This question is easier."],
    ],
  },
  {
    titleJa: "比較 — more / less / than",
    titleEn: "Comparisons — more / less / than",
    cards: [
      ["コーヒーよりお茶の方が好きだ。", "I like tea more than coffee."],
      ["昨日より今日の方が忙しい。", "Today is busier than yesterday."],
      ["彼より私の方が背が高い。", "I'm taller than him."],
      ["これよりあれの方が安い。", "That is cheaper than this."],
      ["仕事より家族の方が大事だ。", "Family is more important than work."],
      ["話すより聞く方が好きだ。", "I prefer listening to speaking."],
      ["夏より秋の方が好きだ。", "I like autumn more than summer."],
      ["彼女の方が経験が多い。", "She has more experience than me."],
      ["時間がもっと欲しい。", "I need more time."],
      ["もっとゆっくり話して。", "Please speak more slowly."],
      ["もっと安いのはありますか？", "Do you have something less expensive?"],
      ["もっと近い駅はありますか？", "Is there a closer station?"],
      ["彼は私より二歳年上だ。", "He is two years older than me."],
    ],
  },
  {
    titleJa: "道順 — turn left / go straight",
    titleEn: "Directions — turn left / go straight",
    cards: [
      ["左に曲がって。", "Turn left."],
      ["右に曲がって。", "Turn right."],
      ["まっすぐ行って。", "Go straight."],
      ["二つ目の角を右へ。", "Turn right at the second corner."],
      ["信号を渡って。", "Cross at the traffic lights."],
      ["この道をずっと行く。", "Go along this street."],
      ["駅はどこですか？", "Where is the station?"],
      ["地図を見せてください。", "Please show me the map."],
      ["ここから遠いですか？", "Is it far from here?"],
      ["歩いて何分ですか？", "How many minutes on foot?"],
      ["バス停はどこですか？", "Where is the bus stop?"],
      ["エレベーターはどこですか？", "Where is the elevator?"],
      ["出口はどちらですか？", "Which way is the exit?"],
    ],
  },
  {
    titleJa: "旅行 — 切符・空港・ホテル",
    titleEn: "Travel — tickets, airport, hotel",
    cards: [
      ["片道の切符をください。", "A one-way ticket, please."],
      ["往復の切符をください。", "A round-trip ticket, please."],
      ["窓口はどこですか？", "Where is the ticket counter?"],
      ["搭乗口は何番ですか？", "What is the gate number?"],
      ["手荷物を預けたい。", "I want to check my bag."],
      ["チェックインをお願いします。", "I'd like to check in, please."],
      ["予約の名前は…です。", "The reservation is under …"],
      ["鍵をください。", "The key, please."],
      ["朝食はついていますか？", "Is breakfast included?"],
      ["Wi-Fiのパスワードは？", "What is the Wi-Fi password?"],
      ["タクシーを呼んでください。", "Please call a taxi."],
      ["空港までお願いします。", "To the airport, please."],
      ["この席、空いていますか？", "Is this seat free?"],
    ],
  },
  {
    titleJa: "買い物とお金 — how much / expensive / cheap",
    titleEn: "Shopping & Money — how much / expensive / cheap",
    cards: [
      ["いくらですか？", "How much is it?"],
      ["高すぎます。", "It's too expensive."],
      ["安いですね。", "It's cheap."],
      ["カードで払えますか？", "Can I pay by card?"],
      ["現金しか使えませんか？", "Is cash only okay?"],
      ["お釣りをください。", "Could I have my change, please?"],
      ["レシートをください。", "A receipt, please."],
      ["サイズを変えたい。", "I'd like a different size."],
      ["返品できますか？", "Can I return this?"],
      ["試着室はどこですか？", "Where is the fitting room?"],
      ["袋はいりますか？", "Do you need a bag?"],
      ["セールはいつまでですか？", "How long is the sale?"],
      ["値引きできますか？", "Can you give me a discount?"],
    ],
  },
  {
    titleJa: "買い物 — 店での会話",
    titleEn: "Shopping — in the store",
    cards: [
      ["何かお手伝いしましょうか？", "Can I help you?"],
      ["これを見せてください。", "Please show me this one."],
      ["他の色はありますか？", "Do you have another color?"],
      ["在庫はありますか？", "Do you have it in stock?"],
      ["これをください。", "I'll take this one."],
      ["まだ見ます。", "I'm just looking."],
      ["おすすめは何ですか？", "What do you recommend?"],
      ["小さいサイズはありますか？", "Do you have a smaller size?"],
      ["試着してもいいですか？", "May I try it on?"],
      ["包装してください。", "Please wrap it."],
      ["ギフト用にしてください。", "It's a gift, please."],
      ["別のを見せてください。", "Please show me another one."],
      ["合計はいくらですか？", "What is the total?"],
    ],
  },
  {
    titleJa: "気持ちと意見 — think / feel / believe",
    titleEn: "Feelings & Opinions — think / feel / believe",
    cards: [
      ["そう思う。", "I think so."],
      ["そうは思わない。", "I don't think so."],
      ["いいと思う。", "I think it's good."],
      ["疲れている気がする。", "I feel tired."],
      ["嬉しい気持ちだ。", "I feel happy."],
      ["心配だ。", "I feel worried."],
      ["それは正しいと信じている。", "I believe that's true."],
      ["自分でできると思う。", "I believe I can do it."],
      ["難しいと思う。", "I think it's difficult."],
      ["簡単だと思う。", "I think it's easy."],
      ["意味がわからない。", "I don't understand the meaning."],
      ["賛成だ。", "I agree."],
      ["反対だ。", "I disagree."],
    ],
  },
  {
    titleJa: "意見を柔らかく言う",
    titleEn: "Soft opinions & hedging",
    cards: [
      ["たぶん大丈夫だと思う。", "I think it's probably okay."],
      ["個人的には好きだ。", "Personally, I like it."],
      ["私の意見では、公平だ。", "In my opinion, it's fair."],
      ["もしかしたら遅れるかもしれない。", "I might be late."],
      ["できるかどうかわからない。", "I'm not sure if I can."],
      ["それは良い考えだと思う。", "I think that's a good idea."],
      ["もう少し時間が欲しい。", "I need a little more time."],
      ["ちょっと考えさせて。", "Let me think about it."],
      ["その方が安全だと思う。", "I think that's safer."],
      ["気分次第だ。", "It depends on how I feel."],
      ["場合による。", "It depends on the situation."],
      ["君の言う通りかもしれない。", "You might be right."],
      ["完全には同意できない。", "I can't fully agree."],
    ],
  },
  {
    titleJa: "依頼 — Can you help me?",
    titleEn: "Requests — Can you help me?",
    cards: [
      ["手伝ってもらえますか？", "Can you help me?"],
      ["これを持ってもらえますか？", "Can you hold this for me?"],
      ["写真を撮ってもらえますか？", "Can you take a photo for me?"],
      ["スペルを教えてもらえますか？", "Can you spell that for me?"],
      ["もう一度言ってもらえますか？", "Can you say that again?"],
      ["窓を開けてもらえますか？", "Can you open the window?"],
      ["ドアを閉めてもらえますか？", "Can you close the door?"],
      ["ここに名前を書いてもらえますか？", "Can you write your name here?"],
      ["遅れないで来てもらえますか？", "Can you come on time?"],
      ["静かにしてもらえますか？", "Can you be quiet?"],
      ["待ってもらえますか？", "Can you wait?"],
      ["これを説明してもらえますか？", "Can you explain this?"],
      ["道を教えてもらえますか？", "Can you tell me the way?"],
    ],
  },
  {
    titleJa: "依頼 — Please give me water",
    titleEn: "Requests — Please give / Could I have",
    cards: [
      ["水をください。", "Please give me water."],
      ["お茶をください。", "Tea, please."],
      ["メニューをください。", "The menu, please."],
      ["おしぼりをください。", "A wet towel, please."],
      ["箸をください。", "Chopsticks, please."],
      ["フォークをください。", "A fork, please."],
      ["お会計をお願いします。", "The check, please."],
      ["袋をください。", "A bag, please."],
      ["コーヒーをもう一杯ください。", "Another coffee, please."],
      ["砂糖を少しください。", "A little sugar, please."],
      ["温かいお茶をいただけますか？", "Could I have some hot tea?"],
      ["お水をいただけますか？", "Could I have some water?"],
      ["こちらにお願いします。", "This one, please."],
    ],
  },
  {
    titleJa: "短い会話 — 店と挨拶",
    titleEn: "Short Dialogues — shop & greetings",
    cards: [
      ["A: いらっしゃいませ。 B: 見ているだけです。", "A: Welcome. B: I'm just looking."],
      ["A: 何かお探しですか？ B: はい、帽子を探しています。", "A: What are you looking for? B: Yes, I'm looking for a hat."],
      ["A: こちらはいかがですか？ B: 試着してもいいですか？", "A: How about this one? B: May I try it on?"],
      ["A: お似合いですよ。 B: ありがとうございます。", "A: It looks good on you. B: Thank you."],
      ["A: 他の色もあります。 B: 青はありますか？", "A: We have other colors. B: Do you have blue?"],
      ["A: サイズは？ B: Mをお願いします。", "A: What size? B: Medium, please."],
      ["A: 包装しますか？ B: お願いします。", "A: Shall I wrap it? B: Yes, please."],
      ["A: カードでよろしいですか？ B: はい、お願いします。", "A: Card? B: Yes, please."],
      ["A: ありがとうございました。 B: またどうぞ。", "A: Thank you for your purchase. B: Please come again."],
      ["A: すみません、値段は？ B: 二千円です。", "A: Excuse me, how much is it? B: It's two thousand yen."],
      ["A: 少し高いです。 B: ではこちらはいかがですか。", "A: It's a bit expensive. B: How about this one?"],
      ["A: 在庫はありますか？ B: はい、ございます。", "A: Do you have it in stock? B: Yes, we do."],
      ["A: 返品はできますか？ B: 一週間以内なら可能です。", "A: Can I return it? B: Yes, within one week."],
    ],
  },
  {
    titleJa: "短い会話 — カフェと食事",
    titleEn: "Short Dialogues — café & food",
    cards: [
      ["A: ご注文は？ B: ラテを一つお願いします。", "A: What would you like? B: One latte, please."],
      ["A: サイズは？ B: グランデで。", "A: What size? B: Grande, please."],
      ["A: こちらでお召し上がりですか？ B: 持ち帰りで。", "A: For here or to go? B: To go, please."],
      ["A: お名前は？ B: ケンです。", "A: Your name? B: Ken."],
      ["A: お待たせしました。 B: ありがとう。", "A: Here you are. B: Thanks."],
      ["A: 砂糖はいりますか？ B: 少しお願いします。", "A: Sugar? B: A little, please."],
      ["A: 温かいものは？ B: スープをください。", "A: Something hot? B: Soup, please."],
      ["A: アレルギーはありますか？ B: 卵はだめです。", "A: Any allergies? B: I can't have eggs."],
      ["A: おすすめは？ B: 今日のパスタがおすすめです。", "A: What do you recommend? B: Today's pasta is good."],
      ["A: お会計お願いします。 B: はい、千二百円です。", "A: The check, please. B: That's twelve hundred yen."],
      ["A: カード使えますか？ B: はい、使えます。", "A: Do you take cards? B: Yes, we do."],
      ["A: テーブル空いてますか？ B: 二人ですか？", "A: Is a table free? B: For two?"],
      ["A: メニューをください。 B: はい、どうぞ。", "A: The menu, please. B: Here you are."],
    ],
  },
  {
    titleJa: "短い会話 — 道案内と助け",
    titleEn: "Short Dialogues — directions & help",
    cards: [
      ["A: すみません、駅はどこですか？ B: まっすぐで、左です。", "A: Excuse me, where is the station? B: Go straight, then left."],
      ["A: 遠いですか？ B: 歩いて十分です。", "A: Is it far? B: About ten minutes on foot."],
      ["A: 地図を見せてください。 B: はい、ここです。", "A: Please show me on the map. B: Yes, here."],
      ["A: タクシー乗り場は？ B: あそこの角です。", "A: Where is the taxi stand? B: Around that corner."],
      ["A: 助けてください！ B: どうしました？", "A: Please help me! B: What's wrong?"],
      ["A: 携帯がないんです。 B: こちらから電話しましょう。", "A: I lost my phone. B: You can call from here."],
      ["A: 道に迷いました。 B: 一緒に地図を見ましょう。", "A: I'm lost. B: Let's look at the map together."],
      ["A: 英語が話せますか？ B: 少しだけです。", "A: Do you speak English? B: A little."],
      ["A: ゆっくり話してください。 B: わかりました。", "A: Please speak slowly. B: Okay."],
      ["A: トイレはどこですか？ B: あちらの階です。", "A: Where is the restroom? B: On that floor over there."],
      ["A: エレベーターは？ B: 右にあります。", "A: Where is the elevator? B: It's on the right."],
      ["A: 危ないですか？ B: いいえ、大丈夫です。", "A: Is it dangerous? B: No, it's fine."],
      ["A: ありがとうございました。 B: どういたしまして。", "A: Thank you so much. B: You're welcome."],
    ],
  },
];

function build() {
  const decks = DECKS.map((d, di) => ({
    id: `study-b3-deck-${di}`,
    titleJa: d.titleJa,
    titleEn: d.titleEn,
    sortOrder: di,
    cards: d.cards.map(([frontJa, backEn], ci) => ({
      id: `study-b3-d${di}-c${ci}`,
      frontJa,
      backEn,
      sortOrder: ci,
    })),
  }));

  const items = [
    {
      id: "study-b3-a0",
      promptJa: "「I went to school yesterday.」に近い日本語は？",
      promptEn: "Which Japanese is closest to “I went to school yesterday.”?",
      options: ["昨日、学校に行く。", "昨日、学校に行った。", "明日、学校に行く。", "今、学校にいる。"],
      correctIndex: 1,
    },
    {
      id: "study-b3-a1",
      promptJa: "「I'm going to travel.」の意味に近いのは？",
      promptEn: "Which Japanese matches “I'm going to travel.”?",
      options: ["旅行した。", "旅行するつもりだ。", "旅行している。", "旅行したくない。"],
      correctIndex: 1,
    },
    {
      id: "study-b3-a2",
      promptJa: "「because」の意味は？",
      promptEn: "What does “because” mean?",
      options: ["だから／なぜなら", "しかし", "それとも", "そのあと"],
      correctIndex: 0,
    },
    {
      id: "study-b3-a3",
      promptJa: "「never」に近い意味は？",
      promptEn: "Which Japanese is closest to “never”?",
      options: ["いつも", "ときどき", "決して〜ない", "よく"],
      correctIndex: 2,
    },
    {
      id: "study-b3-a4",
      promptJa: "「This one is bigger.」に近い日本語は？",
      promptEn: "Which Japanese matches “This one is bigger.”?",
      options: ["これの方が小さい。", "これの方が大きい。", "これは同じだ。", "これは高い。"],
      correctIndex: 1,
    },
    {
      id: "study-b3-a5",
      promptJa: "「Turn left.」は日本語で？",
      promptEn: "Which Japanese matches “Turn left.”?",
      options: ["右に曲がって。", "まっすぐ行って。", "左に曲がって。", "止まって。"],
      correctIndex: 2,
    },
    {
      id: "study-b3-a6",
      promptJa: "「How much is it?」は日本語で？",
      promptEn: "Which Japanese means “How much is it?”?",
      options: ["いつですか？", "どこですか？", "いくらですか？", "何ですか？"],
      correctIndex: 2,
    },
    {
      id: "study-b3-a7",
      promptJa: "「I think so.」に近い日本語は？",
      promptEn: "Which Japanese matches “I think so.”?",
      options: ["そう思う。", "知らない。", "違う。", "忘れた。"],
      correctIndex: 0,
    },
    {
      id: "study-b3-a8",
      promptJa: "「Can you help me?」は日本語で？",
      promptEn: "Which Japanese matches “Can you help me?”?",
      options: ["手伝ってもらえますか？", "さようなら。", "すみません、名前は？", "お腹が空いた。"],
      correctIndex: 0,
    },
    {
      id: "study-b3-a9",
      promptJa: "「Please give me water.」に近い日本語は？",
      promptEn: "Which Japanese matches “Please give me water.”?",
      options: ["水を飲まない。", "水をください。", "水はいらない。", "水はどこ？"],
      correctIndex: 1,
    },
    {
      id: "study-b3-a10",
      promptJa: "「Did you go to work yesterday?」に近い日本語は？",
      promptEn: "Which Japanese matches “Did you go to work yesterday?”?",
      options: ["明日、仕事に行く？", "昨日、仕事に行きましたか？", "今、仕事にいる？", "仕事は好き？"],
      correctIndex: 1,
    },
    {
      id: "study-b3-a11",
      promptJa: "「I like tea more than coffee.」に近い日本語は？",
      promptEn: "Which Japanese matches “I like tea more than coffee.”?",
      options: ["コーヒーしか飲まない。", "コーヒーよりお茶の方が好きだ。", "お茶は嫌いだ。", "コーヒーとお茶は同じだ。"],
      correctIndex: 1,
    },
  ];

  const doc = {
    version: 1 as const,
    levelCode: StudyLevelCode.BEGINNER_3,
    decks,
    assessment: { passingScore: 70, items },
  };

  return beginner3LevelFileSchema.parse(doc);
}

function main() {
  const validated = build();
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, `${JSON.stringify(validated, null, 2)}\n`, "utf8");
  const total = validated.decks.reduce((s, d) => s + d.cards.length, 0);
  console.log(`Wrote ${OUT} (${validated.decks.length} decks, ${total} cards)`);
}

main();
